_target_: loaders.V3C12Loader
name: v3c
v3c_root_folder: "/data1/v3c-collection/selected-frames"
video_root_folder: "/data1/v3c-common-data"

extraction:
  # - model: "omni_embed_nemotron_3B"
  #   modality: "video"
  - model: "omni_embed_nemotron_3B"
    modality: "video+audio"
  - model: "qwen_embedding_8B"
    modality: "video"
  - model: "qwen_embedding_8B"
    modality: "image"
  - model: "openclip_clip_vit_l_14"
    modality: "image"
  - model: "openclip_clip_vit_h_14"
    modality: "image"
  - model: "dinov2_base"
    modality: "image"