database:
  host: localhost:6024
  user: langchain
  password: langchain
  dbname: langchain

embedding:
  server_url: "localhost:1234"
  timeout: 120
  # Define available models here
  models:
    - name: "qwen_embedding_8B"
      dim: 4096
      mrl_dim: 1024
    # - name: "openclip_clip_vit_b_32"
    #   dim: 512
    #   mrl_dim: null 
    - name: "openclip_clip_vit_l_14"
      dim: 768
      mrl_dim: null
    - name: "openclip_clip_vit_h_14"
      dim: 1024
      mrl_dim: null
    - name: "dinov2_base"
      dim: 768
      mrl_dim: null

data:
  server_url: "localhost:4567"
