defaults:
  - loader: ???
  - common
  - _self_

host: localhost
port: 8000
default_k: 100
fts_language: "english"

index_query_options:
  ef_search: 1000
  iterative_scan: "relaxed_order"
  max_scan_tuples: 150000
  random_page_cost: 0.2

translate:
  model: "ministral-3:14b"
  base_url: "localhost:3456"

llm_query:
  model: "ministral-3:14b" #"qwen3.5:9b"
  base_url: "localhost:3456"
  temperature: 0
  default_model: "openclip_clip_vit_b_32"
  leaf_k: 100000
  final_k: 1000

qa:
  model: "ministral-3:14b"
  base_url: "localhost:3456"
  temperature: 0
  max_iterations: 5
  max_total_images: 10
  max_images_per_call: 5
  default_model: "qwen_embedding_8B"
  debug: true

combined_retrieval_models:
  - "name": "smart (qwen + cliph)"
    "models": ["qwen_embedding_8B", "openclip_clip_vit_h_14"]
    "extended_k": 100000
    "modalities": ["text", "image"]