/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiAnswer } from './ApiAnswer';
import {
    ApiAnswerFromJSON,
    ApiAnswerFromJSONTyped,
    ApiAnswerToJSON,
    ApiAnswerToJSONTyped,
} from './ApiAnswer';
import type { ApiVerdictStatus } from './ApiVerdictStatus';
import {
    ApiVerdictStatusFromJSON,
    ApiVerdictStatusFromJSONTyped,
    ApiVerdictStatusToJSON,
    ApiVerdictStatusToJSONTyped,
} from './ApiVerdictStatus';

/**
 * 
 * @export
 * @interface ApiAnswerSet
 */
export interface ApiAnswerSet {
    /**
     * 
     * @type {string}
     * @memberof ApiAnswerSet
     */
    id: string;
    /**
     * 
     * @type {ApiVerdictStatus}
     * @memberof ApiAnswerSet
     */
    status: ApiVerdictStatus;
    /**
     * 
     * @type {string}
     * @memberof ApiAnswerSet
     */
    taskId: string;
    /**
     * 
     * @type {Array<ApiAnswer>}
     * @memberof ApiAnswerSet
     */
    answers: Array<ApiAnswer>;
}



/**
 * Check if a given object implements the ApiAnswerSet interface.
 */
export function instanceOfApiAnswerSet(value: object): value is ApiAnswerSet {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('taskId' in value) || value['taskId'] === undefined) return false;
    if (!('answers' in value) || value['answers'] === undefined) return false;
    return true;
}

export function ApiAnswerSetFromJSON(json: any): ApiAnswerSet {
    return ApiAnswerSetFromJSONTyped(json, false);
}

export function ApiAnswerSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAnswerSet {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': ApiVerdictStatusFromJSON(json['status']),
        'taskId': json['taskId'],
        'answers': ((json['answers'] as Array<any>).map(ApiAnswerFromJSON)),
    };
}

export function ApiAnswerSetToJSON(json: any): ApiAnswerSet {
    return ApiAnswerSetToJSONTyped(json, false);
}

export function ApiAnswerSetToJSONTyped(value?: ApiAnswerSet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': ApiVerdictStatusToJSON(value['status']),
        'taskId': value['taskId'],
        'answers': ((value['answers'] as Array<any>).map(ApiAnswerToJSON)),
    };
}

