/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApiAnswerType = {
    Item: 'ITEM',
    Temporal: 'TEMPORAL',
    Text: 'TEXT'
} as const;
export type ApiAnswerType = typeof ApiAnswerType[keyof typeof ApiAnswerType];


export function instanceOfApiAnswerType(value: any): boolean {
    for (const key in ApiAnswerType) {
        if (Object.prototype.hasOwnProperty.call(ApiAnswerType, key)) {
            if (ApiAnswerType[key as keyof typeof ApiAnswerType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiAnswerTypeFromJSON(json: any): ApiAnswerType {
    return ApiAnswerTypeFromJSONTyped(json, false);
}

export function ApiAnswerTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAnswerType {
    return json as ApiAnswerType;
}

export function ApiAnswerTypeToJSON(value?: ApiAnswerType | null): any {
    return value as any;
}

export function ApiAnswerTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiAnswerType {
    return value as ApiAnswerType;
}

