/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMediaItem } from './ApiMediaItem';
import {
    ApiMediaItemFromJSON,
    ApiMediaItemFromJSONTyped,
    ApiMediaItemToJSON,
    ApiMediaItemToJSONTyped,
} from './ApiMediaItem';
import type { TemporalRange } from './TemporalRange';
import {
    TemporalRangeFromJSON,
    TemporalRangeFromJSONTyped,
    TemporalRangeToJSON,
    TemporalRangeToJSONTyped,
} from './TemporalRange';
import type { ApiAnswerType } from './ApiAnswerType';
import {
    ApiAnswerTypeFromJSON,
    ApiAnswerTypeFromJSONTyped,
    ApiAnswerTypeToJSON,
    ApiAnswerTypeToJSONTyped,
} from './ApiAnswerType';

/**
 * 
 * @export
 * @interface ApiAnswer
 */
export interface ApiAnswer {
    /**
     * 
     * @type {ApiAnswerType}
     * @memberof ApiAnswer
     */
    type: ApiAnswerType;
    /**
     * 
     * @type {ApiMediaItem}
     * @memberof ApiAnswer
     */
    item?: ApiMediaItem;
    /**
     * 
     * @type {string}
     * @memberof ApiAnswer
     */
    text?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiAnswer
     */
    start?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiAnswer
     */
    end?: number;
    /**
     * 
     * @type {TemporalRange}
     * @memberof ApiAnswer
     */
    temporalRange?: TemporalRange;
}



/**
 * Check if a given object implements the ApiAnswer interface.
 */
export function instanceOfApiAnswer(value: object): value is ApiAnswer {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ApiAnswerFromJSON(json: any): ApiAnswer {
    return ApiAnswerFromJSONTyped(json, false);
}

export function ApiAnswerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAnswer {
    if (json == null) {
        return json;
    }
    return {
        
        'type': ApiAnswerTypeFromJSON(json['type']),
        'item': json['item'] == null ? undefined : ApiMediaItemFromJSON(json['item']),
        'text': json['text'] == null ? undefined : json['text'],
        'start': json['start'] == null ? undefined : json['start'],
        'end': json['end'] == null ? undefined : json['end'],
        'temporalRange': json['temporalRange'] == null ? undefined : TemporalRangeFromJSON(json['temporalRange']),
    };
}

export function ApiAnswerToJSON(json: any): ApiAnswer {
    return ApiAnswerToJSONTyped(json, false);
}

export function ApiAnswerToJSONTyped(value?: ApiAnswer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': ApiAnswerTypeToJSON(value['type']),
        'item': ApiMediaItemToJSON(value['item']),
        'text': value['text'],
        'start': value['start'],
        'end': value['end'],
        'temporalRange': TemporalRangeToJSON(value['temporalRange']),
    };
}

