/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiContentType } from './ApiContentType';
import {
    ApiContentTypeFromJSON,
    ApiContentTypeFromJSONTyped,
    ApiContentTypeToJSON,
    ApiContentTypeToJSONTyped,
} from './ApiContentType';

/**
 * 
 * @export
 * @interface ApiContentElement
 */
export interface ApiContentElement {
    /**
     * 
     * @type {ApiContentType}
     * @memberof ApiContentElement
     */
    contentType: ApiContentType;
    /**
     * 
     * @type {string}
     * @memberof ApiContentElement
     */
    content?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiContentElement
     */
    offset: number;
}



/**
 * Check if a given object implements the ApiContentElement interface.
 */
export function instanceOfApiContentElement(value: object): value is ApiContentElement {
    if (!('contentType' in value) || value['contentType'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    return true;
}

export function ApiContentElementFromJSON(json: any): ApiContentElement {
    return ApiContentElementFromJSONTyped(json, false);
}

export function ApiContentElementFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiContentElement {
    if (json == null) {
        return json;
    }
    return {
        
        'contentType': ApiContentTypeFromJSON(json['contentType']),
        'content': json['content'] == null ? undefined : json['content'],
        'offset': json['offset'],
    };
}

export function ApiContentElementToJSON(json: any): ApiContentElement {
    return ApiContentElementToJSONTyped(json, false);
}

export function ApiContentElementToJSONTyped(value?: ApiContentElement | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contentType': ApiContentTypeToJSON(value['contentType']),
        'content': value['content'],
        'offset': value['offset'],
    };
}

