/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiClientAnswer
 */
export interface ApiClientAnswer {
    /**
     * 
     * @type {string}
     * @memberof ApiClientAnswer
     */
    text?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiClientAnswer
     */
    mediaItemName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiClientAnswer
     */
    mediaItemCollectionName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiClientAnswer
     */
    start?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ApiClientAnswer
     */
    end?: number | null;
}

/**
 * Check if a given object implements the ApiClientAnswer interface.
 */
export function instanceOfApiClientAnswer(value: object): value is ApiClientAnswer {
    return true;
}

export function ApiClientAnswerFromJSON(json: any): ApiClientAnswer {
    return ApiClientAnswerFromJSONTyped(json, false);
}

export function ApiClientAnswerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiClientAnswer {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
        'mediaItemName': json['mediaItemName'] == null ? undefined : json['mediaItemName'],
        'mediaItemCollectionName': json['mediaItemCollectionName'] == null ? undefined : json['mediaItemCollectionName'],
        'start': json['start'] == null ? undefined : json['start'],
        'end': json['end'] == null ? undefined : json['end'],
    };
}

export function ApiClientAnswerToJSON(json: any): ApiClientAnswer {
    return ApiClientAnswerToJSONTyped(json, false);
}

export function ApiClientAnswerToJSONTyped(value?: ApiClientAnswer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'mediaItemName': value['mediaItemName'],
        'mediaItemCollectionName': value['mediaItemCollectionName'],
        'start': value['start'],
        'end': value['end'],
    };
}

