/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiClientAnswer } from './ApiClientAnswer';
import {
    ApiClientAnswerFromJSON,
    ApiClientAnswerFromJSONTyped,
    ApiClientAnswerToJSON,
    ApiClientAnswerToJSONTyped,
} from './ApiClientAnswer';

/**
 * 
 * @export
 * @interface ApiClientAnswerSet
 */
export interface ApiClientAnswerSet {
    /**
     * 
     * @type {string}
     * @memberof ApiClientAnswerSet
     */
    taskId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiClientAnswerSet
     */
    taskName?: string | null;
    /**
     * 
     * @type {Array<ApiClientAnswer>}
     * @memberof ApiClientAnswerSet
     */
    answers: Array<ApiClientAnswer>;
}

/**
 * Check if a given object implements the ApiClientAnswerSet interface.
 */
export function instanceOfApiClientAnswerSet(value: object): value is ApiClientAnswerSet {
    if (!('answers' in value) || value['answers'] === undefined) return false;
    return true;
}

export function ApiClientAnswerSetFromJSON(json: any): ApiClientAnswerSet {
    return ApiClientAnswerSetFromJSONTyped(json, false);
}

export function ApiClientAnswerSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiClientAnswerSet {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['taskId'] == null ? undefined : json['taskId'],
        'taskName': json['taskName'] == null ? undefined : json['taskName'],
        'answers': ((json['answers'] as Array<any>).map(ApiClientAnswerFromJSON)),
    };
}

export function ApiClientAnswerSetToJSON(json: any): ApiClientAnswerSet {
    return ApiClientAnswerSetToJSONTyped(json, false);
}

export function ApiClientAnswerSetToJSONTyped(value?: ApiClientAnswerSet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'taskId': value['taskId'],
        'taskName': value['taskName'],
        'answers': ((value['answers'] as Array<any>).map(ApiClientAnswerToJSON)),
    };
}

