/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiClientTaskTemplateInfo
 */
export interface ApiClientTaskTemplateInfo {
    /**
     * 
     * @type {string}
     * @memberof ApiClientTaskTemplateInfo
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ApiClientTaskTemplateInfo
     */
    taskGroup: string;
    /**
     * 
     * @type {string}
     * @memberof ApiClientTaskTemplateInfo
     */
    taskType: string;
    /**
     * 
     * @type {number}
     * @memberof ApiClientTaskTemplateInfo
     */
    duration: number;
}

/**
 * Check if a given object implements the ApiClientTaskTemplateInfo interface.
 */
export function instanceOfApiClientTaskTemplateInfo(value: object): value is ApiClientTaskTemplateInfo {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('taskGroup' in value) || value['taskGroup'] === undefined) return false;
    if (!('taskType' in value) || value['taskType'] === undefined) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    return true;
}

export function ApiClientTaskTemplateInfoFromJSON(json: any): ApiClientTaskTemplateInfo {
    return ApiClientTaskTemplateInfoFromJSONTyped(json, false);
}

export function ApiClientTaskTemplateInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiClientTaskTemplateInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'taskGroup': json['taskGroup'],
        'taskType': json['taskType'],
        'duration': json['duration'],
    };
}

export function ApiClientTaskTemplateInfoToJSON(json: any): ApiClientTaskTemplateInfo {
    return ApiClientTaskTemplateInfoToJSONTyped(json, false);
}

export function ApiClientTaskTemplateInfoToJSONTyped(value?: ApiClientTaskTemplateInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'taskGroup': value['taskGroup'],
        'taskType': value['taskType'],
        'duration': value['duration'],
    };
}

