/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiCreateEvaluation
 */
export interface ApiCreateEvaluation {
    /**
     * 
     * @type {string}
     * @memberof ApiCreateEvaluation
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ApiCreateEvaluation
     */
    description: string;
}

/**
 * Check if a given object implements the ApiCreateEvaluation interface.
 */
export function instanceOfApiCreateEvaluation(value: object): value is ApiCreateEvaluation {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function ApiCreateEvaluationFromJSON(json: any): ApiCreateEvaluation {
    return ApiCreateEvaluationFromJSONTyped(json, false);
}

export function ApiCreateEvaluationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiCreateEvaluation {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
    };
}

export function ApiCreateEvaluationToJSON(json: any): ApiCreateEvaluation {
    return ApiCreateEvaluationToJSONTyped(json, false);
}

export function ApiCreateEvaluationToJSONTyped(value?: ApiCreateEvaluation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

