/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiClientAnswerSet } from './ApiClientAnswerSet';
import {
    ApiClientAnswerSetFromJSON,
    ApiClientAnswerSetFromJSONTyped,
    ApiClientAnswerSetToJSON,
    ApiClientAnswerSetToJSONTyped,
} from './ApiClientAnswerSet';

/**
 * 
 * @export
 * @interface ApiClientSubmission
 */
export interface ApiClientSubmission {
    /**
     * 
     * @type {Array<ApiClientAnswerSet>}
     * @memberof ApiClientSubmission
     */
    answerSets: Array<ApiClientAnswerSet>;
}

/**
 * Check if a given object implements the ApiClientSubmission interface.
 */
export function instanceOfApiClientSubmission(value: object): value is ApiClientSubmission {
    if (!('answerSets' in value) || value['answerSets'] === undefined) return false;
    return true;
}

export function ApiClientSubmissionFromJSON(json: any): ApiClientSubmission {
    return ApiClientSubmissionFromJSONTyped(json, false);
}

export function ApiClientSubmissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiClientSubmission {
    if (json == null) {
        return json;
    }
    return {
        
        'answerSets': ((json['answerSets'] as Array<any>).map(ApiClientAnswerSetFromJSON)),
    };
}

export function ApiClientSubmissionToJSON(json: any): ApiClientSubmission {
    return ApiClientSubmissionToJSONTyped(json, false);
}

export function ApiClientSubmissionToJSONTyped(value?: ApiClientSubmission | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'answerSets': ((value['answerSets'] as Array<any>).map(ApiClientAnswerSetToJSON)),
    };
}

