/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApiContentType = {
    Empty: 'EMPTY',
    Text: 'TEXT',
    Video: 'VIDEO',
    Image: 'IMAGE'
} as const;
export type ApiContentType = typeof ApiContentType[keyof typeof ApiContentType];


export function instanceOfApiContentType(value: any): boolean {
    for (const key in ApiContentType) {
        if (Object.prototype.hasOwnProperty.call(ApiContentType, key)) {
            if (ApiContentType[key as keyof typeof ApiContentType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiContentTypeFromJSON(json: any): ApiContentType {
    return ApiContentTypeFromJSONTyped(json, false);
}

export function ApiContentTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiContentType {
    return json as ApiContentType;
}

export function ApiContentTypeToJSON(value?: ApiContentType | null): any {
    return value as any;
}

export function ApiContentTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiContentType {
    return value as ApiContentType;
}

