/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiClientTaskTemplateInfo } from './ApiClientTaskTemplateInfo';
import {
    ApiClientTaskTemplateInfoFromJSON,
    ApiClientTaskTemplateInfoFromJSONTyped,
    ApiClientTaskTemplateInfoToJSON,
    ApiClientTaskTemplateInfoToJSONTyped,
} from './ApiClientTaskTemplateInfo';
import type { ApiEvaluationStatus } from './ApiEvaluationStatus';
import {
    ApiEvaluationStatusFromJSON,
    ApiEvaluationStatusFromJSONTyped,
    ApiEvaluationStatusToJSON,
    ApiEvaluationStatusToJSONTyped,
} from './ApiEvaluationStatus';
import type { ApiEvaluationType } from './ApiEvaluationType';
import {
    ApiEvaluationTypeFromJSON,
    ApiEvaluationTypeFromJSONTyped,
    ApiEvaluationTypeToJSON,
    ApiEvaluationTypeToJSONTyped,
} from './ApiEvaluationType';

/**
 * 
 * @export
 * @interface ApiClientEvaluationInfo
 */
export interface ApiClientEvaluationInfo {
    /**
     * 
     * @type {string}
     * @memberof ApiClientEvaluationInfo
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApiClientEvaluationInfo
     */
    name: string;
    /**
     * 
     * @type {ApiEvaluationType}
     * @memberof ApiClientEvaluationInfo
     */
    type: ApiEvaluationType;
    /**
     * 
     * @type {ApiEvaluationStatus}
     * @memberof ApiClientEvaluationInfo
     */
    status: ApiEvaluationStatus;
    /**
     * 
     * @type {string}
     * @memberof ApiClientEvaluationInfo
     */
    templateId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiClientEvaluationInfo
     */
    templateDescription?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiClientEvaluationInfo
     */
    teams: Array<string>;
    /**
     * 
     * @type {Array<ApiClientTaskTemplateInfo>}
     * @memberof ApiClientEvaluationInfo
     */
    taskTemplates: Array<ApiClientTaskTemplateInfo>;
}



/**
 * Check if a given object implements the ApiClientEvaluationInfo interface.
 */
export function instanceOfApiClientEvaluationInfo(value: object): value is ApiClientEvaluationInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('templateId' in value) || value['templateId'] === undefined) return false;
    if (!('teams' in value) || value['teams'] === undefined) return false;
    if (!('taskTemplates' in value) || value['taskTemplates'] === undefined) return false;
    return true;
}

export function ApiClientEvaluationInfoFromJSON(json: any): ApiClientEvaluationInfo {
    return ApiClientEvaluationInfoFromJSONTyped(json, false);
}

export function ApiClientEvaluationInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiClientEvaluationInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'type': ApiEvaluationTypeFromJSON(json['type']),
        'status': ApiEvaluationStatusFromJSON(json['status']),
        'templateId': json['templateId'],
        'templateDescription': json['templateDescription'] == null ? undefined : json['templateDescription'],
        'teams': json['teams'],
        'taskTemplates': ((json['taskTemplates'] as Array<any>).map(ApiClientTaskTemplateInfoFromJSON)),
    };
}

export function ApiClientEvaluationInfoToJSON(json: any): ApiClientEvaluationInfo {
    return ApiClientEvaluationInfoToJSONTyped(json, false);
}

export function ApiClientEvaluationInfoToJSONTyped(value?: ApiClientEvaluationInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': ApiEvaluationTypeToJSON(value['type']),
        'status': ApiEvaluationStatusToJSON(value['status']),
        'templateId': value['templateId'],
        'templateDescription': value['templateDescription'],
        'teams': value['teams'],
        'taskTemplates': ((value['taskTemplates'] as Array<any>).map(ApiClientTaskTemplateInfoToJSON)),
    };
}

