/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiTask } from './ApiTask';
import {
    ApiTaskFromJSON,
    ApiTaskFromJSONTyped,
    ApiTaskToJSON,
    ApiTaskToJSONTyped,
} from './ApiTask';
import type { ApiEvaluationType } from './ApiEvaluationType';
import {
    ApiEvaluationTypeFromJSON,
    ApiEvaluationTypeFromJSONTyped,
    ApiEvaluationTypeToJSON,
    ApiEvaluationTypeToJSONTyped,
} from './ApiEvaluationType';
import type { ApiEvaluationTemplate } from './ApiEvaluationTemplate';
import {
    ApiEvaluationTemplateFromJSON,
    ApiEvaluationTemplateFromJSONTyped,
    ApiEvaluationTemplateToJSON,
    ApiEvaluationTemplateToJSONTyped,
} from './ApiEvaluationTemplate';

/**
 * 
 * @export
 * @interface ApiEvaluation
 */
export interface ApiEvaluation {
    /**
     * 
     * @type {string}
     * @memberof ApiEvaluation
     */
    evaluationId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiEvaluation
     */
    name: string;
    /**
     * 
     * @type {ApiEvaluationType}
     * @memberof ApiEvaluation
     */
    type: ApiEvaluationType;
    /**
     * 
     * @type {ApiEvaluationTemplate}
     * @memberof ApiEvaluation
     */
    template: ApiEvaluationTemplate;
    /**
     * 
     * @type {number}
     * @memberof ApiEvaluation
     */
    created: number;
    /**
     * 
     * @type {number}
     * @memberof ApiEvaluation
     */
    started?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiEvaluation
     */
    ended?: number;
    /**
     * 
     * @type {Array<ApiTask>}
     * @memberof ApiEvaluation
     */
    tasks: Array<ApiTask>;
}



/**
 * Check if a given object implements the ApiEvaluation interface.
 */
export function instanceOfApiEvaluation(value: object): value is ApiEvaluation {
    if (!('evaluationId' in value) || value['evaluationId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('template' in value) || value['template'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('tasks' in value) || value['tasks'] === undefined) return false;
    return true;
}

export function ApiEvaluationFromJSON(json: any): ApiEvaluation {
    return ApiEvaluationFromJSONTyped(json, false);
}

export function ApiEvaluationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiEvaluation {
    if (json == null) {
        return json;
    }
    return {
        
        'evaluationId': json['evaluationId'],
        'name': json['name'],
        'type': ApiEvaluationTypeFromJSON(json['type']),
        'template': ApiEvaluationTemplateFromJSON(json['template']),
        'created': json['created'],
        'started': json['started'] == null ? undefined : json['started'],
        'ended': json['ended'] == null ? undefined : json['ended'],
        'tasks': ((json['tasks'] as Array<any>).map(ApiTaskFromJSON)),
    };
}

export function ApiEvaluationToJSON(json: any): ApiEvaluation {
    return ApiEvaluationToJSONTyped(json, false);
}

export function ApiEvaluationToJSONTyped(value?: ApiEvaluation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'evaluationId': value['evaluationId'],
        'name': value['name'],
        'type': ApiEvaluationTypeToJSON(value['type']),
        'template': ApiEvaluationTemplateToJSON(value['template']),
        'created': value['created'],
        'started': value['started'],
        'ended': value['ended'],
        'tasks': ((value['tasks'] as Array<any>).map(ApiTaskToJSON)),
    };
}

