/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiTaskGroup } from './ApiTaskGroup';
import {
    ApiTaskGroupFromJSON,
    ApiTaskGroupFromJSONTyped,
    ApiTaskGroupToJSON,
    ApiTaskGroupToJSONTyped,
} from './ApiTaskGroup';
import type { ApiTaskTemplate } from './ApiTaskTemplate';
import {
    ApiTaskTemplateFromJSON,
    ApiTaskTemplateFromJSONTyped,
    ApiTaskTemplateToJSON,
    ApiTaskTemplateToJSONTyped,
} from './ApiTaskTemplate';
import type { ApiTeam } from './ApiTeam';
import {
    ApiTeamFromJSON,
    ApiTeamFromJSONTyped,
    ApiTeamToJSON,
    ApiTeamToJSONTyped,
} from './ApiTeam';
import type { ApiTaskType } from './ApiTaskType';
import {
    ApiTaskTypeFromJSON,
    ApiTaskTypeFromJSONTyped,
    ApiTaskTypeToJSON,
    ApiTaskTypeToJSONTyped,
} from './ApiTaskType';
import type { ApiTeamGroup } from './ApiTeamGroup';
import {
    ApiTeamGroupFromJSON,
    ApiTeamGroupFromJSONTyped,
    ApiTeamGroupToJSON,
    ApiTeamGroupToJSONTyped,
} from './ApiTeamGroup';

/**
 * 
 * @export
 * @interface ApiEvaluationTemplate
 */
export interface ApiEvaluationTemplate {
    /**
     * 
     * @type {string}
     * @memberof ApiEvaluationTemplate
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApiEvaluationTemplate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ApiEvaluationTemplate
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiEvaluationTemplate
     */
    created?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiEvaluationTemplate
     */
    modified?: number;
    /**
     * 
     * @type {Array<ApiTaskType>}
     * @memberof ApiEvaluationTemplate
     */
    taskTypes: Array<ApiTaskType>;
    /**
     * 
     * @type {Array<ApiTaskGroup>}
     * @memberof ApiEvaluationTemplate
     */
    taskGroups: Array<ApiTaskGroup>;
    /**
     * 
     * @type {Array<ApiTaskTemplate>}
     * @memberof ApiEvaluationTemplate
     */
    tasks: Array<ApiTaskTemplate>;
    /**
     * 
     * @type {Array<ApiTeam>}
     * @memberof ApiEvaluationTemplate
     */
    teams: Array<ApiTeam>;
    /**
     * 
     * @type {Array<ApiTeamGroup>}
     * @memberof ApiEvaluationTemplate
     */
    teamGroups: Array<ApiTeamGroup>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiEvaluationTemplate
     */
    judges: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiEvaluationTemplate
     */
    viewers: Array<string>;
}

/**
 * Check if a given object implements the ApiEvaluationTemplate interface.
 */
export function instanceOfApiEvaluationTemplate(value: object): value is ApiEvaluationTemplate {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('taskTypes' in value) || value['taskTypes'] === undefined) return false;
    if (!('taskGroups' in value) || value['taskGroups'] === undefined) return false;
    if (!('tasks' in value) || value['tasks'] === undefined) return false;
    if (!('teams' in value) || value['teams'] === undefined) return false;
    if (!('teamGroups' in value) || value['teamGroups'] === undefined) return false;
    if (!('judges' in value) || value['judges'] === undefined) return false;
    if (!('viewers' in value) || value['viewers'] === undefined) return false;
    return true;
}

export function ApiEvaluationTemplateFromJSON(json: any): ApiEvaluationTemplate {
    return ApiEvaluationTemplateFromJSONTyped(json, false);
}

export function ApiEvaluationTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiEvaluationTemplate {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'created': json['created'] == null ? undefined : json['created'],
        'modified': json['modified'] == null ? undefined : json['modified'],
        'taskTypes': ((json['taskTypes'] as Array<any>).map(ApiTaskTypeFromJSON)),
        'taskGroups': ((json['taskGroups'] as Array<any>).map(ApiTaskGroupFromJSON)),
        'tasks': ((json['tasks'] as Array<any>).map(ApiTaskTemplateFromJSON)),
        'teams': ((json['teams'] as Array<any>).map(ApiTeamFromJSON)),
        'teamGroups': ((json['teamGroups'] as Array<any>).map(ApiTeamGroupFromJSON)),
        'judges': json['judges'],
        'viewers': json['viewers'],
    };
}

export function ApiEvaluationTemplateToJSON(json: any): ApiEvaluationTemplate {
    return ApiEvaluationTemplateToJSONTyped(json, false);
}

export function ApiEvaluationTemplateToJSONTyped(value?: ApiEvaluationTemplate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'created': value['created'],
        'modified': value['modified'],
        'taskTypes': ((value['taskTypes'] as Array<any>).map(ApiTaskTypeToJSON)),
        'taskGroups': ((value['taskGroups'] as Array<any>).map(ApiTaskGroupToJSON)),
        'tasks': ((value['tasks'] as Array<any>).map(ApiTaskTemplateToJSON)),
        'teams': ((value['teams'] as Array<any>).map(ApiTeamToJSON)),
        'teamGroups': ((value['teamGroups'] as Array<any>).map(ApiTeamGroupToJSON)),
        'judges': value['judges'],
        'viewers': value['viewers'],
    };
}

