/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiEvaluationTemplateOverview
 */
export interface ApiEvaluationTemplateOverview {
    /**
     * 
     * @type {string}
     * @memberof ApiEvaluationTemplateOverview
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApiEvaluationTemplateOverview
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ApiEvaluationTemplateOverview
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiEvaluationTemplateOverview
     */
    taskCount: number;
    /**
     * 
     * @type {number}
     * @memberof ApiEvaluationTemplateOverview
     */
    teamCount: number;
}

/**
 * Check if a given object implements the ApiEvaluationTemplateOverview interface.
 */
export function instanceOfApiEvaluationTemplateOverview(value: object): value is ApiEvaluationTemplateOverview {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('taskCount' in value) || value['taskCount'] === undefined) return false;
    if (!('teamCount' in value) || value['teamCount'] === undefined) return false;
    return true;
}

export function ApiEvaluationTemplateOverviewFromJSON(json: any): ApiEvaluationTemplateOverview {
    return ApiEvaluationTemplateOverviewFromJSONTyped(json, false);
}

export function ApiEvaluationTemplateOverviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiEvaluationTemplateOverview {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'taskCount': json['taskCount'],
        'teamCount': json['teamCount'],
    };
}

export function ApiEvaluationTemplateOverviewToJSON(json: any): ApiEvaluationTemplateOverview {
    return ApiEvaluationTemplateOverviewToJSONTyped(json, false);
}

export function ApiEvaluationTemplateOverviewToJSONTyped(value?: ApiEvaluationTemplateOverview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'taskCount': value['taskCount'],
        'teamCount': value['teamCount'],
    };
}

