/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiTeamInfo } from './ApiTeamInfo';
import {
    ApiTeamInfoFromJSON,
    ApiTeamInfoFromJSONTyped,
    ApiTeamInfoToJSON,
    ApiTeamInfoToJSONTyped,
} from './ApiTeamInfo';
import type { ApiEvaluationStatus } from './ApiEvaluationStatus';
import {
    ApiEvaluationStatusFromJSON,
    ApiEvaluationStatusFromJSONTyped,
    ApiEvaluationStatusToJSON,
    ApiEvaluationStatusToJSONTyped,
} from './ApiEvaluationStatus';
import type { ApiTaskTemplateInfo } from './ApiTaskTemplateInfo';
import {
    ApiTaskTemplateInfoFromJSON,
    ApiTaskTemplateInfoFromJSONTyped,
    ApiTaskTemplateInfoToJSON,
    ApiTaskTemplateInfoToJSONTyped,
} from './ApiTaskTemplateInfo';
import type { ApiRunProperties } from './ApiRunProperties';
import {
    ApiRunPropertiesFromJSON,
    ApiRunPropertiesFromJSONTyped,
    ApiRunPropertiesToJSON,
    ApiRunPropertiesToJSONTyped,
} from './ApiRunProperties';
import type { ApiEvaluationType } from './ApiEvaluationType';
import {
    ApiEvaluationTypeFromJSON,
    ApiEvaluationTypeFromJSONTyped,
    ApiEvaluationTypeToJSON,
    ApiEvaluationTypeToJSONTyped,
} from './ApiEvaluationType';

/**
 * 
 * @export
 * @interface ApiEvaluationInfo
 */
export interface ApiEvaluationInfo {
    /**
     * 
     * @type {string}
     * @memberof ApiEvaluationInfo
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApiEvaluationInfo
     */
    name: string;
    /**
     * 
     * @type {ApiEvaluationType}
     * @memberof ApiEvaluationInfo
     */
    type: ApiEvaluationType;
    /**
     * 
     * @type {ApiEvaluationStatus}
     * @memberof ApiEvaluationInfo
     */
    status: ApiEvaluationStatus;
    /**
     * 
     * @type {ApiRunProperties}
     * @memberof ApiEvaluationInfo
     */
    properties: ApiRunProperties;
    /**
     * 
     * @type {string}
     * @memberof ApiEvaluationInfo
     */
    templateId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiEvaluationInfo
     */
    templateDescription?: string;
    /**
     * 
     * @type {Array<ApiTeamInfo>}
     * @memberof ApiEvaluationInfo
     */
    teams: Array<ApiTeamInfo>;
    /**
     * 
     * @type {Array<ApiTaskTemplateInfo>}
     * @memberof ApiEvaluationInfo
     */
    taskTemplates: Array<ApiTaskTemplateInfo>;
}



/**
 * Check if a given object implements the ApiEvaluationInfo interface.
 */
export function instanceOfApiEvaluationInfo(value: object): value is ApiEvaluationInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('properties' in value) || value['properties'] === undefined) return false;
    if (!('templateId' in value) || value['templateId'] === undefined) return false;
    if (!('teams' in value) || value['teams'] === undefined) return false;
    if (!('taskTemplates' in value) || value['taskTemplates'] === undefined) return false;
    return true;
}

export function ApiEvaluationInfoFromJSON(json: any): ApiEvaluationInfo {
    return ApiEvaluationInfoFromJSONTyped(json, false);
}

export function ApiEvaluationInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiEvaluationInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'type': ApiEvaluationTypeFromJSON(json['type']),
        'status': ApiEvaluationStatusFromJSON(json['status']),
        'properties': ApiRunPropertiesFromJSON(json['properties']),
        'templateId': json['templateId'],
        'templateDescription': json['templateDescription'] == null ? undefined : json['templateDescription'],
        'teams': ((json['teams'] as Array<any>).map(ApiTeamInfoFromJSON)),
        'taskTemplates': ((json['taskTemplates'] as Array<any>).map(ApiTaskTemplateInfoFromJSON)),
    };
}

export function ApiEvaluationInfoToJSON(json: any): ApiEvaluationInfo {
    return ApiEvaluationInfoToJSONTyped(json, false);
}

export function ApiEvaluationInfoToJSONTyped(value?: ApiEvaluationInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': ApiEvaluationTypeToJSON(value['type']),
        'status': ApiEvaluationStatusToJSON(value['status']),
        'properties': ApiRunPropertiesToJSON(value['properties']),
        'templateId': value['templateId'],
        'templateDescription': value['templateDescription'],
        'teams': ((value['teams'] as Array<any>).map(ApiTeamInfoToJSON)),
        'taskTemplates': ((value['taskTemplates'] as Array<any>).map(ApiTaskTemplateInfoToJSON)),
    };
}

