/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApiEvaluationType = {
    Synchronous: 'SYNCHRONOUS',
    Asynchronous: 'ASYNCHRONOUS',
    NonInteractive: 'NON_INTERACTIVE'
} as const;
export type ApiEvaluationType = typeof ApiEvaluationType[keyof typeof ApiEvaluationType];


export function instanceOfApiEvaluationType(value: any): boolean {
    for (const key in ApiEvaluationType) {
        if (Object.prototype.hasOwnProperty.call(ApiEvaluationType, key)) {
            if (ApiEvaluationType[key as keyof typeof ApiEvaluationType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiEvaluationTypeFromJSON(json: any): ApiEvaluationType {
    return ApiEvaluationTypeFromJSONTyped(json, false);
}

export function ApiEvaluationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiEvaluationType {
    return json as ApiEvaluationType;
}

export function ApiEvaluationTypeToJSON(value?: ApiEvaluationType | null): any {
    return value as any;
}

export function ApiEvaluationTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiEvaluationType {
    return value as ApiEvaluationType;
}

