/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RunManagerStatus } from './RunManagerStatus';
import {
    RunManagerStatusFromJSON,
    RunManagerStatusFromJSONTyped,
    RunManagerStatusToJSON,
    RunManagerStatusToJSONTyped,
} from './RunManagerStatus';
import type { ApiTeamTaskOverview } from './ApiTeamTaskOverview';
import {
    ApiTeamTaskOverviewFromJSON,
    ApiTeamTaskOverviewFromJSONTyped,
    ApiTeamTaskOverviewToJSON,
    ApiTeamTaskOverviewToJSONTyped,
} from './ApiTeamTaskOverview';

/**
 * 
 * @export
 * @interface ApiEvaluationOverview
 */
export interface ApiEvaluationOverview {
    /**
     * 
     * @type {RunManagerStatus}
     * @memberof ApiEvaluationOverview
     */
    state: RunManagerStatus;
    /**
     * 
     * @type {Array<ApiTeamTaskOverview>}
     * @memberof ApiEvaluationOverview
     */
    teamOverviews: Array<ApiTeamTaskOverview>;
}



/**
 * Check if a given object implements the ApiEvaluationOverview interface.
 */
export function instanceOfApiEvaluationOverview(value: object): value is ApiEvaluationOverview {
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('teamOverviews' in value) || value['teamOverviews'] === undefined) return false;
    return true;
}

export function ApiEvaluationOverviewFromJSON(json: any): ApiEvaluationOverview {
    return ApiEvaluationOverviewFromJSONTyped(json, false);
}

export function ApiEvaluationOverviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiEvaluationOverview {
    if (json == null) {
        return json;
    }
    return {
        
        'state': RunManagerStatusFromJSON(json['state']),
        'teamOverviews': ((json['teamOverviews'] as Array<any>).map(ApiTeamTaskOverviewFromJSON)),
    };
}

export function ApiEvaluationOverviewToJSON(json: any): ApiEvaluationOverview {
    return ApiEvaluationOverviewToJSONTyped(json, false);
}

export function ApiEvaluationOverviewToJSONTyped(value?: ApiEvaluationOverview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'state': RunManagerStatusToJSON(value['state']),
        'teamOverviews': ((value['teamOverviews'] as Array<any>).map(ApiTeamTaskOverviewToJSON)),
    };
}

