/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApiEvaluationStatus = {
    Created: 'CREATED',
    Active: 'ACTIVE',
    Terminated: 'TERMINATED'
} as const;
export type ApiEvaluationStatus = typeof ApiEvaluationStatus[keyof typeof ApiEvaluationStatus];


export function instanceOfApiEvaluationStatus(value: any): boolean {
    for (const key in ApiEvaluationStatus) {
        if (Object.prototype.hasOwnProperty.call(ApiEvaluationStatus, key)) {
            if (ApiEvaluationStatus[key as keyof typeof ApiEvaluationStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiEvaluationStatusFromJSON(json: any): ApiEvaluationStatus {
    return ApiEvaluationStatusFromJSONTyped(json, false);
}

export function ApiEvaluationStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiEvaluationStatus {
    return json as ApiEvaluationStatus;
}

export function ApiEvaluationStatusToJSON(value?: ApiEvaluationStatus | null): any {
    return value as any;
}

export function ApiEvaluationStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiEvaluationStatus {
    return value as ApiEvaluationStatus;
}

