/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiEvaluationStatus } from './ApiEvaluationStatus';
import {
    ApiEvaluationStatusFromJSON,
    ApiEvaluationStatusFromJSONTyped,
    ApiEvaluationStatusToJSON,
    ApiEvaluationStatusToJSONTyped,
} from './ApiEvaluationStatus';
import type { ApiTaskStatus } from './ApiTaskStatus';
import {
    ApiTaskStatusFromJSON,
    ApiTaskStatusFromJSONTyped,
    ApiTaskStatusToJSON,
    ApiTaskStatusToJSONTyped,
} from './ApiTaskStatus';

/**
 * 
 * @export
 * @interface ApiEvaluationState
 */
export interface ApiEvaluationState {
    /**
     * 
     * @type {string}
     * @memberof ApiEvaluationState
     */
    evaluationId: string;
    /**
     * 
     * @type {ApiEvaluationStatus}
     * @memberof ApiEvaluationState
     */
    evaluationStatus: ApiEvaluationStatus;
    /**
     * 
     * @type {string}
     * @memberof ApiEvaluationState
     */
    taskId?: string;
    /**
     * 
     * @type {ApiTaskStatus}
     * @memberof ApiEvaluationState
     */
    taskStatus: ApiTaskStatus;
    /**
     * 
     * @type {string}
     * @memberof ApiEvaluationState
     */
    taskTemplateId?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiEvaluationState
     */
    timeLeft: number;
    /**
     * 
     * @type {number}
     * @memberof ApiEvaluationState
     */
    timeElapsed: number;
}



/**
 * Check if a given object implements the ApiEvaluationState interface.
 */
export function instanceOfApiEvaluationState(value: object): value is ApiEvaluationState {
    if (!('evaluationId' in value) || value['evaluationId'] === undefined) return false;
    if (!('evaluationStatus' in value) || value['evaluationStatus'] === undefined) return false;
    if (!('taskStatus' in value) || value['taskStatus'] === undefined) return false;
    if (!('timeLeft' in value) || value['timeLeft'] === undefined) return false;
    if (!('timeElapsed' in value) || value['timeElapsed'] === undefined) return false;
    return true;
}

export function ApiEvaluationStateFromJSON(json: any): ApiEvaluationState {
    return ApiEvaluationStateFromJSONTyped(json, false);
}

export function ApiEvaluationStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiEvaluationState {
    if (json == null) {
        return json;
    }
    return {
        
        'evaluationId': json['evaluationId'],
        'evaluationStatus': ApiEvaluationStatusFromJSON(json['evaluationStatus']),
        'taskId': json['taskId'] == null ? undefined : json['taskId'],
        'taskStatus': ApiTaskStatusFromJSON(json['taskStatus']),
        'taskTemplateId': json['taskTemplateId'] == null ? undefined : json['taskTemplateId'],
        'timeLeft': json['timeLeft'],
        'timeElapsed': json['timeElapsed'],
    };
}

export function ApiEvaluationStateToJSON(json: any): ApiEvaluationState {
    return ApiEvaluationStateToJSONTyped(json, false);
}

export function ApiEvaluationStateToJSONTyped(value?: ApiEvaluationState | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'evaluationId': value['evaluationId'],
        'evaluationStatus': ApiEvaluationStatusToJSON(value['evaluationStatus']),
        'taskId': value['taskId'],
        'taskStatus': ApiTaskStatusToJSON(value['taskStatus']),
        'taskTemplateId': value['taskTemplateId'],
        'timeLeft': value['timeLeft'],
        'timeElapsed': value['timeElapsed'],
    };
}

