/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiRunProperties } from './ApiRunProperties';
import {
    ApiRunPropertiesFromJSON,
    ApiRunPropertiesFromJSONTyped,
    ApiRunPropertiesToJSON,
    ApiRunPropertiesToJSONTyped,
} from './ApiRunProperties';
import type { ApiEvaluationType } from './ApiEvaluationType';
import {
    ApiEvaluationTypeFromJSON,
    ApiEvaluationTypeFromJSONTyped,
    ApiEvaluationTypeToJSON,
    ApiEvaluationTypeToJSONTyped,
} from './ApiEvaluationType';

/**
 * 
 * @export
 * @interface ApiEvaluationStartMessage
 */
export interface ApiEvaluationStartMessage {
    /**
     * 
     * @type {string}
     * @memberof ApiEvaluationStartMessage
     */
    templateId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiEvaluationStartMessage
     */
    name: string;
    /**
     * 
     * @type {ApiEvaluationType}
     * @memberof ApiEvaluationStartMessage
     */
    type: ApiEvaluationType;
    /**
     * 
     * @type {ApiRunProperties}
     * @memberof ApiEvaluationStartMessage
     */
    properties: ApiRunProperties;
}



/**
 * Check if a given object implements the ApiEvaluationStartMessage interface.
 */
export function instanceOfApiEvaluationStartMessage(value: object): value is ApiEvaluationStartMessage {
    if (!('templateId' in value) || value['templateId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('properties' in value) || value['properties'] === undefined) return false;
    return true;
}

export function ApiEvaluationStartMessageFromJSON(json: any): ApiEvaluationStartMessage {
    return ApiEvaluationStartMessageFromJSONTyped(json, false);
}

export function ApiEvaluationStartMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiEvaluationStartMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'templateId': json['templateId'],
        'name': json['name'],
        'type': ApiEvaluationTypeFromJSON(json['type']),
        'properties': ApiRunPropertiesFromJSON(json['properties']),
    };
}

export function ApiEvaluationStartMessageToJSON(json: any): ApiEvaluationStartMessage {
    return ApiEvaluationStartMessageToJSONTyped(json, false);
}

export function ApiEvaluationStartMessageToJSONTyped(value?: ApiEvaluationStartMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'templateId': value['templateId'],
        'name': value['name'],
        'type': ApiEvaluationTypeToJSON(value['type']),
        'properties': ApiRunPropertiesToJSON(value['properties']),
    };
}

