/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApiHintOption = {
    ImageItem: 'IMAGE_ITEM',
    VideoItemSegment: 'VIDEO_ITEM_SEGMENT',
    Text: 'TEXT',
    ExternalImage: 'EXTERNAL_IMAGE',
    ExternalVideo: 'EXTERNAL_VIDEO'
} as const;
export type ApiHintOption = typeof ApiHintOption[keyof typeof ApiHintOption];


export function instanceOfApiHintOption(value: any): boolean {
    for (const key in ApiHintOption) {
        if (Object.prototype.hasOwnProperty.call(ApiHintOption, key)) {
            if (ApiHintOption[key as keyof typeof ApiHintOption] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiHintOptionFromJSON(json: any): ApiHintOption {
    return ApiHintOptionFromJSONTyped(json, false);
}

export function ApiHintOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiHintOption {
    return json as ApiHintOption;
}

export function ApiHintOptionToJSON(value?: ApiHintOption | null): any {
    return value as any;
}

export function ApiHintOptionToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiHintOption {
    return value as ApiHintOption;
}

