/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApiHintType = {
    Empty: 'EMPTY',
    Text: 'TEXT',
    Video: 'VIDEO',
    Image: 'IMAGE'
} as const;
export type ApiHintType = typeof ApiHintType[keyof typeof ApiHintType];


export function instanceOfApiHintType(value: any): boolean {
    for (const key in ApiHintType) {
        if (Object.prototype.hasOwnProperty.call(ApiHintType, key)) {
            if (ApiHintType[key as keyof typeof ApiHintType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiHintTypeFromJSON(json: any): ApiHintType {
    return ApiHintTypeFromJSONTyped(json, false);
}

export function ApiHintTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiHintType {
    return json as ApiHintType;
}

export function ApiHintTypeToJSON(value?: ApiHintType | null): any {
    return value as any;
}

export function ApiHintTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiHintType {
    return value as ApiHintType;
}

