/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiContentElement } from './ApiContentElement';
import {
    ApiContentElementFromJSON,
    ApiContentElementFromJSONTyped,
    ApiContentElementToJSON,
    ApiContentElementToJSONTyped,
} from './ApiContentElement';

/**
 * 
 * @export
 * @interface ApiHintContent
 */
export interface ApiHintContent {
    /**
     * 
     * @type {string}
     * @memberof ApiHintContent
     */
    taskId: string;
    /**
     * 
     * @type {Array<ApiContentElement>}
     * @memberof ApiHintContent
     */
    sequence: Array<ApiContentElement>;
    /**
     * 
     * @type {boolean}
     * @memberof ApiHintContent
     */
    loop: boolean;
}

/**
 * Check if a given object implements the ApiHintContent interface.
 */
export function instanceOfApiHintContent(value: object): value is ApiHintContent {
    if (!('taskId' in value) || value['taskId'] === undefined) return false;
    if (!('sequence' in value) || value['sequence'] === undefined) return false;
    if (!('loop' in value) || value['loop'] === undefined) return false;
    return true;
}

export function ApiHintContentFromJSON(json: any): ApiHintContent {
    return ApiHintContentFromJSONTyped(json, false);
}

export function ApiHintContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiHintContent {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['taskId'],
        'sequence': ((json['sequence'] as Array<any>).map(ApiContentElementFromJSON)),
        'loop': json['loop'],
    };
}

export function ApiHintContentToJSON(json: any): ApiHintContent {
    return ApiHintContentToJSONTyped(json, false);
}

export function ApiHintContentToJSONTyped(value?: ApiHintContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'taskId': value['taskId'],
        'sequence': ((value['sequence'] as Array<any>).map(ApiContentElementToJSON)),
        'loop': value['loop'],
    };
}

