/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiTemporalRange } from './ApiTemporalRange';
import {
    ApiTemporalRangeFromJSON,
    ApiTemporalRangeFromJSONTyped,
    ApiTemporalRangeToJSON,
    ApiTemporalRangeToJSONTyped,
} from './ApiTemporalRange';
import type { ApiMediaItem } from './ApiMediaItem';
import {
    ApiMediaItemFromJSON,
    ApiMediaItemFromJSONTyped,
    ApiMediaItemToJSON,
    ApiMediaItemToJSONTyped,
} from './ApiMediaItem';
import type { ApiHintType } from './ApiHintType';
import {
    ApiHintTypeFromJSON,
    ApiHintTypeFromJSONTyped,
    ApiHintTypeToJSON,
    ApiHintTypeToJSONTyped,
} from './ApiHintType';

/**
 * 
 * @export
 * @interface ApiHint
 */
export interface ApiHint {
    /**
     * 
     * @type {ApiHintType}
     * @memberof ApiHint
     */
    type: ApiHintType;
    /**
     * 
     * @type {number}
     * @memberof ApiHint
     */
    start?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiHint
     */
    end?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiHint
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiHint
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiHint
     */
    dataType?: string;
    /**
     * 
     * @type {ApiMediaItem}
     * @memberof ApiHint
     */
    item?: ApiMediaItem;
    /**
     * 
     * @type {ApiTemporalRange}
     * @memberof ApiHint
     */
    range?: ApiTemporalRange;
}



/**
 * Check if a given object implements the ApiHint interface.
 */
export function instanceOfApiHint(value: object): value is ApiHint {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ApiHintFromJSON(json: any): ApiHint {
    return ApiHintFromJSONTyped(json, false);
}

export function ApiHintFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiHint {
    if (json == null) {
        return json;
    }
    return {
        
        'type': ApiHintTypeFromJSON(json['type']),
        'start': json['start'] == null ? undefined : json['start'],
        'end': json['end'] == null ? undefined : json['end'],
        'description': json['description'] == null ? undefined : json['description'],
        'path': json['path'] == null ? undefined : json['path'],
        'dataType': json['dataType'] == null ? undefined : json['dataType'],
        'item': json['item'] == null ? undefined : ApiMediaItemFromJSON(json['item']),
        'range': json['range'] == null ? undefined : ApiTemporalRangeFromJSON(json['range']),
    };
}

export function ApiHintToJSON(json: any): ApiHint {
    return ApiHintToJSONTyped(json, false);
}

export function ApiHintToJSONTyped(value?: ApiHint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': ApiHintTypeToJSON(value['type']),
        'start': value['start'],
        'end': value['end'],
        'description': value['description'],
        'path': value['path'],
        'dataType': value['dataType'],
        'item': ApiMediaItemToJSON(value['item']),
        'range': ApiTemporalRangeToJSON(value['range']),
    };
}

