/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiAnswerSet } from './ApiAnswerSet';
import {
    ApiAnswerSetFromJSON,
    ApiAnswerSetFromJSONTyped,
    ApiAnswerSetToJSON,
    ApiAnswerSetToJSONTyped,
} from './ApiAnswerSet';

/**
 * 
 * @export
 * @interface ApiJudgementRequest
 */
export interface ApiJudgementRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiJudgementRequest
     */
    token?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiJudgementRequest
     */
    validator: string;
    /**
     * 
     * @type {string}
     * @memberof ApiJudgementRequest
     */
    taskDescription: string;
    /**
     * 
     * @type {ApiAnswerSet}
     * @memberof ApiJudgementRequest
     */
    answerSet: ApiAnswerSet;
}

/**
 * Check if a given object implements the ApiJudgementRequest interface.
 */
export function instanceOfApiJudgementRequest(value: object): value is ApiJudgementRequest {
    if (!('validator' in value) || value['validator'] === undefined) return false;
    if (!('taskDescription' in value) || value['taskDescription'] === undefined) return false;
    if (!('answerSet' in value) || value['answerSet'] === undefined) return false;
    return true;
}

export function ApiJudgementRequestFromJSON(json: any): ApiJudgementRequest {
    return ApiJudgementRequestFromJSONTyped(json, false);
}

export function ApiJudgementRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiJudgementRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
        'validator': json['validator'],
        'taskDescription': json['taskDescription'],
        'answerSet': ApiAnswerSetFromJSON(json['answerSet']),
    };
}

export function ApiJudgementRequestToJSON(json: any): ApiJudgementRequest {
    return ApiJudgementRequestToJSONTyped(json, false);
}

export function ApiJudgementRequestToJSONTyped(value?: ApiJudgementRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'validator': value['validator'],
        'taskDescription': value['taskDescription'],
        'answerSet': ApiAnswerSetToJSON(value['answerSet']),
    };
}

