/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiVerdictStatus } from './ApiVerdictStatus';
import {
    ApiVerdictStatusFromJSON,
    ApiVerdictStatusFromJSONTyped,
    ApiVerdictStatusToJSON,
    ApiVerdictStatusToJSONTyped,
} from './ApiVerdictStatus';

/**
 * 
 * @export
 * @interface ApiJudgement
 */
export interface ApiJudgement {
    /**
     * 
     * @type {string}
     * @memberof ApiJudgement
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof ApiJudgement
     */
    validator: string;
    /**
     * 
     * @type {ApiVerdictStatus}
     * @memberof ApiJudgement
     */
    verdict: ApiVerdictStatus;
}



/**
 * Check if a given object implements the ApiJudgement interface.
 */
export function instanceOfApiJudgement(value: object): value is ApiJudgement {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('validator' in value) || value['validator'] === undefined) return false;
    if (!('verdict' in value) || value['verdict'] === undefined) return false;
    return true;
}

export function ApiJudgementFromJSON(json: any): ApiJudgement {
    return ApiJudgementFromJSONTyped(json, false);
}

export function ApiJudgementFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiJudgement {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'validator': json['validator'],
        'verdict': ApiVerdictStatusFromJSON(json['verdict']),
    };
}

export function ApiJudgementToJSON(json: any): ApiJudgement {
    return ApiJudgementToJSONTyped(json, false);
}

export function ApiJudgementToJSONTyped(value?: ApiJudgement | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'validator': value['validator'],
        'verdict': ApiVerdictStatusToJSON(value['verdict']),
    };
}

