/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiJudgementValidatorStatus
 */
export interface ApiJudgementValidatorStatus {
    /**
     * 
     * @type {string}
     * @memberof ApiJudgementValidatorStatus
     */
    validatorName: string;
    /**
     * 
     * @type {number}
     * @memberof ApiJudgementValidatorStatus
     */
    pending: number;
    /**
     * 
     * @type {number}
     * @memberof ApiJudgementValidatorStatus
     */
    open: number;
}

/**
 * Check if a given object implements the ApiJudgementValidatorStatus interface.
 */
export function instanceOfApiJudgementValidatorStatus(value: object): value is ApiJudgementValidatorStatus {
    if (!('validatorName' in value) || value['validatorName'] === undefined) return false;
    if (!('pending' in value) || value['pending'] === undefined) return false;
    if (!('open' in value) || value['open'] === undefined) return false;
    return true;
}

export function ApiJudgementValidatorStatusFromJSON(json: any): ApiJudgementValidatorStatus {
    return ApiJudgementValidatorStatusFromJSONTyped(json, false);
}

export function ApiJudgementValidatorStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiJudgementValidatorStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'validatorName': json['validatorName'],
        'pending': json['pending'],
        'open': json['open'],
    };
}

export function ApiJudgementValidatorStatusToJSON(json: any): ApiJudgementValidatorStatus {
    return ApiJudgementValidatorStatusToJSONTyped(json, false);
}

export function ApiJudgementValidatorStatusToJSONTyped(value?: ApiJudgementValidatorStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'validatorName': value['validatorName'],
        'pending': value['pending'],
        'open': value['open'],
    };
}

