/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiMediaCollection
 */
export interface ApiMediaCollection {
    /**
     * 
     * @type {string}
     * @memberof ApiMediaCollection
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMediaCollection
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMediaCollection
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMediaCollection
     */
    basePath?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiMediaCollection
     */
    itemCount: number;
}

/**
 * Check if a given object implements the ApiMediaCollection interface.
 */
export function instanceOfApiMediaCollection(value: object): value is ApiMediaCollection {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('itemCount' in value) || value['itemCount'] === undefined) return false;
    return true;
}

export function ApiMediaCollectionFromJSON(json: any): ApiMediaCollection {
    return ApiMediaCollectionFromJSONTyped(json, false);
}

export function ApiMediaCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiMediaCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'basePath': json['basePath'] == null ? undefined : json['basePath'],
        'itemCount': json['itemCount'],
    };
}

export function ApiMediaCollectionToJSON(json: any): ApiMediaCollection {
    return ApiMediaCollectionToJSONTyped(json, false);
}

export function ApiMediaCollectionToJSONTyped(value?: ApiMediaCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'basePath': value['basePath'],
        'itemCount': value['itemCount'],
    };
}

