/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApiMediaType = {
    Image: 'IMAGE',
    Video: 'VIDEO',
    Text: 'TEXT'
} as const;
export type ApiMediaType = typeof ApiMediaType[keyof typeof ApiMediaType];


export function instanceOfApiMediaType(value: any): boolean {
    for (const key in ApiMediaType) {
        if (Object.prototype.hasOwnProperty.call(ApiMediaType, key)) {
            if (ApiMediaType[key as keyof typeof ApiMediaType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiMediaTypeFromJSON(json: any): ApiMediaType {
    return ApiMediaTypeFromJSONTyped(json, false);
}

export function ApiMediaTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiMediaType {
    return json as ApiMediaType;
}

export function ApiMediaTypeToJSON(value?: ApiMediaType | null): any {
    return value as any;
}

export function ApiMediaTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiMediaType {
    return value as ApiMediaType;
}

