/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiMediaItemMetaDataEntry
 */
export interface ApiMediaItemMetaDataEntry {
    /**
     * 
     * @type {string}
     * @memberof ApiMediaItemMetaDataEntry
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMediaItemMetaDataEntry
     */
    value: string;
}

/**
 * Check if a given object implements the ApiMediaItemMetaDataEntry interface.
 */
export function instanceOfApiMediaItemMetaDataEntry(value: object): value is ApiMediaItemMetaDataEntry {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function ApiMediaItemMetaDataEntryFromJSON(json: any): ApiMediaItemMetaDataEntry {
    return ApiMediaItemMetaDataEntryFromJSONTyped(json, false);
}

export function ApiMediaItemMetaDataEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiMediaItemMetaDataEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': json['value'],
    };
}

export function ApiMediaItemMetaDataEntryToJSON(json: any): ApiMediaItemMetaDataEntry {
    return ApiMediaItemMetaDataEntryToJSONTyped(json, false);
}

export function ApiMediaItemMetaDataEntryToJSONTyped(value?: ApiMediaItemMetaDataEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'value': value['value'],
    };
}

