/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMediaItemMetaDataEntry } from './ApiMediaItemMetaDataEntry';
import {
    ApiMediaItemMetaDataEntryFromJSON,
    ApiMediaItemMetaDataEntryFromJSONTyped,
    ApiMediaItemMetaDataEntryToJSON,
    ApiMediaItemMetaDataEntryToJSONTyped,
} from './ApiMediaItemMetaDataEntry';
import type { ApiMediaType } from './ApiMediaType';
import {
    ApiMediaTypeFromJSON,
    ApiMediaTypeFromJSONTyped,
    ApiMediaTypeToJSON,
    ApiMediaTypeToJSONTyped,
} from './ApiMediaType';

/**
 * 
 * @export
 * @interface ApiMediaItem
 */
export interface ApiMediaItem {
    /**
     * 
     * @type {string}
     * @memberof ApiMediaItem
     */
    mediaItemId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMediaItem
     */
    name: string;
    /**
     * 
     * @type {ApiMediaType}
     * @memberof ApiMediaItem
     */
    type: ApiMediaType;
    /**
     * 
     * @type {string}
     * @memberof ApiMediaItem
     */
    collectionId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMediaItem
     */
    location: string;
    /**
     * 
     * @type {number}
     * @memberof ApiMediaItem
     */
    durationMs?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiMediaItem
     */
    fps?: number;
    /**
     * 
     * @type {Array<ApiMediaItemMetaDataEntry>}
     * @memberof ApiMediaItem
     */
    metadata: Array<ApiMediaItemMetaDataEntry>;
}



/**
 * Check if a given object implements the ApiMediaItem interface.
 */
export function instanceOfApiMediaItem(value: object): value is ApiMediaItem {
    if (!('mediaItemId' in value) || value['mediaItemId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('collectionId' in value) || value['collectionId'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function ApiMediaItemFromJSON(json: any): ApiMediaItem {
    return ApiMediaItemFromJSONTyped(json, false);
}

export function ApiMediaItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiMediaItem {
    if (json == null) {
        return json;
    }
    return {
        
        'mediaItemId': json['mediaItemId'],
        'name': json['name'],
        'type': ApiMediaTypeFromJSON(json['type']),
        'collectionId': json['collectionId'],
        'location': json['location'],
        'durationMs': json['durationMs'] == null ? undefined : json['durationMs'],
        'fps': json['fps'] == null ? undefined : json['fps'],
        'metadata': ((json['metadata'] as Array<any>).map(ApiMediaItemMetaDataEntryFromJSON)),
    };
}

export function ApiMediaItemToJSON(json: any): ApiMediaItem {
    return ApiMediaItemToJSONTyped(json, false);
}

export function ApiMediaItemToJSONTyped(value?: ApiMediaItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mediaItemId': value['mediaItemId'],
        'name': value['name'],
        'type': ApiMediaTypeToJSON(value['type']),
        'collectionId': value['collectionId'],
        'location': value['location'],
        'durationMs': value['durationMs'],
        'fps': value['fps'],
        'metadata': ((value['metadata'] as Array<any>).map(ApiMediaItemMetaDataEntryToJSON)),
    };
}

