/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiVerdictStatus } from './ApiVerdictStatus';
import {
    ApiVerdictStatusFromJSON,
    ApiVerdictStatusFromJSONTyped,
    ApiVerdictStatusToJSON,
    ApiVerdictStatusToJSONTyped,
} from './ApiVerdictStatus';

/**
 * 
 * @export
 * @interface ApiOverrideAnswerSetVerdictDto
 */
export interface ApiOverrideAnswerSetVerdictDto {
    /**
     * 
     * @type {ApiVerdictStatus}
     * @memberof ApiOverrideAnswerSetVerdictDto
     */
    verdict: ApiVerdictStatus;
}



/**
 * Check if a given object implements the ApiOverrideAnswerSetVerdictDto interface.
 */
export function instanceOfApiOverrideAnswerSetVerdictDto(value: object): value is ApiOverrideAnswerSetVerdictDto {
    if (!('verdict' in value) || value['verdict'] === undefined) return false;
    return true;
}

export function ApiOverrideAnswerSetVerdictDtoFromJSON(json: any): ApiOverrideAnswerSetVerdictDto {
    return ApiOverrideAnswerSetVerdictDtoFromJSONTyped(json, false);
}

export function ApiOverrideAnswerSetVerdictDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiOverrideAnswerSetVerdictDto {
    if (json == null) {
        return json;
    }
    return {
        
        'verdict': ApiVerdictStatusFromJSON(json['verdict']),
    };
}

export function ApiOverrideAnswerSetVerdictDtoToJSON(json: any): ApiOverrideAnswerSetVerdictDto {
    return ApiOverrideAnswerSetVerdictDtoToJSONTyped(json, false);
}

export function ApiOverrideAnswerSetVerdictDtoToJSONTyped(value?: ApiOverrideAnswerSetVerdictDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verdict': ApiVerdictStatusToJSON(value['verdict']),
    };
}

