/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMediaCollection } from './ApiMediaCollection';
import {
    ApiMediaCollectionFromJSON,
    ApiMediaCollectionFromJSONTyped,
    ApiMediaCollectionToJSON,
    ApiMediaCollectionToJSONTyped,
} from './ApiMediaCollection';
import type { ApiMediaItem } from './ApiMediaItem';
import {
    ApiMediaItemFromJSON,
    ApiMediaItemFromJSONTyped,
    ApiMediaItemToJSON,
    ApiMediaItemToJSONTyped,
} from './ApiMediaItem';

/**
 * 
 * @export
 * @interface ApiPopulatedMediaCollection
 */
export interface ApiPopulatedMediaCollection {
    /**
     * 
     * @type {ApiMediaCollection}
     * @memberof ApiPopulatedMediaCollection
     */
    collection: ApiMediaCollection;
    /**
     * 
     * @type {Array<ApiMediaItem>}
     * @memberof ApiPopulatedMediaCollection
     */
    items: Array<ApiMediaItem>;
}

/**
 * Check if a given object implements the ApiPopulatedMediaCollection interface.
 */
export function instanceOfApiPopulatedMediaCollection(value: object): value is ApiPopulatedMediaCollection {
    if (!('collection' in value) || value['collection'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ApiPopulatedMediaCollectionFromJSON(json: any): ApiPopulatedMediaCollection {
    return ApiPopulatedMediaCollectionFromJSONTyped(json, false);
}

export function ApiPopulatedMediaCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiPopulatedMediaCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'collection': ApiMediaCollectionFromJSON(json['collection']),
        'items': ((json['items'] as Array<any>).map(ApiMediaItemFromJSON)),
    };
}

export function ApiPopulatedMediaCollectionToJSON(json: any): ApiPopulatedMediaCollection {
    return ApiPopulatedMediaCollectionToJSONTyped(json, false);
}

export function ApiPopulatedMediaCollectionToJSONTyped(value?: ApiPopulatedMediaCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collection': ApiMediaCollectionToJSON(value['collection']),
        'items': ((value['items'] as Array<any>).map(ApiMediaItemToJSON)),
    };
}

