/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiRunProperties
 */
export interface ApiRunProperties {
    /**
     * 
     * @type {boolean}
     * @memberof ApiRunProperties
     */
    participantCanView: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiRunProperties
     */
    shuffleTasks: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiRunProperties
     */
    allowRepeatedTasks: boolean;
    /**
     * 
     * @type {number}
     * @memberof ApiRunProperties
     */
    limitSubmissionPreviews: number;
}

/**
 * Check if a given object implements the ApiRunProperties interface.
 */
export function instanceOfApiRunProperties(value: object): value is ApiRunProperties {
    if (!('participantCanView' in value) || value['participantCanView'] === undefined) return false;
    if (!('shuffleTasks' in value) || value['shuffleTasks'] === undefined) return false;
    if (!('allowRepeatedTasks' in value) || value['allowRepeatedTasks'] === undefined) return false;
    if (!('limitSubmissionPreviews' in value) || value['limitSubmissionPreviews'] === undefined) return false;
    return true;
}

export function ApiRunPropertiesFromJSON(json: any): ApiRunProperties {
    return ApiRunPropertiesFromJSONTyped(json, false);
}

export function ApiRunPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRunProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'participantCanView': json['participantCanView'],
        'shuffleTasks': json['shuffleTasks'],
        'allowRepeatedTasks': json['allowRepeatedTasks'],
        'limitSubmissionPreviews': json['limitSubmissionPreviews'],
    };
}

export function ApiRunPropertiesToJSON(json: any): ApiRunProperties {
    return ApiRunPropertiesToJSONTyped(json, false);
}

export function ApiRunPropertiesToJSONTyped(value?: ApiRunProperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'participantCanView': value['participantCanView'],
        'shuffleTasks': value['shuffleTasks'],
        'allowRepeatedTasks': value['allowRepeatedTasks'],
        'limitSubmissionPreviews': value['limitSubmissionPreviews'],
    };
}

