/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApiRole = {
    Anyone: 'ANYONE',
    Viewer: 'VIEWER',
    Participant: 'PARTICIPANT',
    Judge: 'JUDGE',
    Admin: 'ADMIN'
} as const;
export type ApiRole = typeof ApiRole[keyof typeof ApiRole];


export function instanceOfApiRole(value: any): boolean {
    for (const key in ApiRole) {
        if (Object.prototype.hasOwnProperty.call(ApiRole, key)) {
            if (ApiRole[key as keyof typeof ApiRole] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiRoleFromJSON(json: any): ApiRole {
    return ApiRoleFromJSONTyped(json, false);
}

export function ApiRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRole {
    return json as ApiRole;
}

export function ApiRoleToJSON(value?: ApiRole | null): any {
    return value as any;
}

export function ApiRoleToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiRole {
    return value as ApiRole;
}

