/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApiScoreOption = {
    Kis: 'KIS',
    Avs: 'AVS',
    LegacyAvs: 'LEGACY_AVS'
} as const;
export type ApiScoreOption = typeof ApiScoreOption[keyof typeof ApiScoreOption];


export function instanceOfApiScoreOption(value: any): boolean {
    for (const key in ApiScoreOption) {
        if (Object.prototype.hasOwnProperty.call(ApiScoreOption, key)) {
            if (ApiScoreOption[key as keyof typeof ApiScoreOption] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiScoreOptionFromJSON(json: any): ApiScoreOption {
    return ApiScoreOptionFromJSONTyped(json, false);
}

export function ApiScoreOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiScoreOption {
    return json as ApiScoreOption;
}

export function ApiScoreOptionToJSON(value?: ApiScoreOption | null): any {
    return value as any;
}

export function ApiScoreOptionToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiScoreOption {
    return value as ApiScoreOption;
}

