/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiScoreSeriesPoint
 */
export interface ApiScoreSeriesPoint {
    /**
     * 
     * @type {number}
     * @memberof ApiScoreSeriesPoint
     */
    score: number;
    /**
     * 
     * @type {number}
     * @memberof ApiScoreSeriesPoint
     */
    timestamp: number;
}

/**
 * Check if a given object implements the ApiScoreSeriesPoint interface.
 */
export function instanceOfApiScoreSeriesPoint(value: object): value is ApiScoreSeriesPoint {
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function ApiScoreSeriesPointFromJSON(json: any): ApiScoreSeriesPoint {
    return ApiScoreSeriesPointFromJSONTyped(json, false);
}

export function ApiScoreSeriesPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiScoreSeriesPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'score': json['score'],
        'timestamp': json['timestamp'],
    };
}

export function ApiScoreSeriesPointToJSON(json: any): ApiScoreSeriesPoint {
    return ApiScoreSeriesPointToJSONTyped(json, false);
}

export function ApiScoreSeriesPointToJSONTyped(value?: ApiScoreSeriesPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'score': value['score'],
        'timestamp': value['timestamp'],
    };
}

