/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiScoreSeriesPoint } from './ApiScoreSeriesPoint';
import {
    ApiScoreSeriesPointFromJSON,
    ApiScoreSeriesPointFromJSONTyped,
    ApiScoreSeriesPointToJSON,
    ApiScoreSeriesPointToJSONTyped,
} from './ApiScoreSeriesPoint';

/**
 * 
 * @export
 * @interface ApiScoreSeries
 */
export interface ApiScoreSeries {
    /**
     * 
     * @type {string}
     * @memberof ApiScoreSeries
     */
    team: string;
    /**
     * 
     * @type {string}
     * @memberof ApiScoreSeries
     */
    name: string;
    /**
     * 
     * @type {Array<ApiScoreSeriesPoint>}
     * @memberof ApiScoreSeries
     */
    points: Array<ApiScoreSeriesPoint>;
}

/**
 * Check if a given object implements the ApiScoreSeries interface.
 */
export function instanceOfApiScoreSeries(value: object): value is ApiScoreSeries {
    if (!('team' in value) || value['team'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('points' in value) || value['points'] === undefined) return false;
    return true;
}

export function ApiScoreSeriesFromJSON(json: any): ApiScoreSeries {
    return ApiScoreSeriesFromJSONTyped(json, false);
}

export function ApiScoreSeriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiScoreSeries {
    if (json == null) {
        return json;
    }
    return {
        
        'team': json['team'],
        'name': json['name'],
        'points': ((json['points'] as Array<any>).map(ApiScoreSeriesPointFromJSON)),
    };
}

export function ApiScoreSeriesToJSON(json: any): ApiScoreSeries {
    return ApiScoreSeriesToJSONTyped(json, false);
}

export function ApiScoreSeriesToJSONTyped(value?: ApiScoreSeries | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'team': value['team'],
        'name': value['name'],
        'points': ((value['points'] as Array<any>).map(ApiScoreSeriesPointToJSON)),
    };
}

