/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApiSubmissionOption = {
    NoDuplicates: 'NO_DUPLICATES',
    LimitCorrectPerTeam: 'LIMIT_CORRECT_PER_TEAM',
    LimitWrongPerTeam: 'LIMIT_WRONG_PER_TEAM',
    LimitTotalPerTeam: 'LIMIT_TOTAL_PER_TEAM',
    LimitCorrectPerMember: 'LIMIT_CORRECT_PER_MEMBER',
    TemporalSubmission: 'TEMPORAL_SUBMISSION',
    TextualSubmission: 'TEXTUAL_SUBMISSION',
    ItemSubmission: 'ITEM_SUBMISSION',
    MinimumTimeGap: 'MINIMUM_TIME_GAP'
} as const;
export type ApiSubmissionOption = typeof ApiSubmissionOption[keyof typeof ApiSubmissionOption];


export function instanceOfApiSubmissionOption(value: any): boolean {
    for (const key in ApiSubmissionOption) {
        if (Object.prototype.hasOwnProperty.call(ApiSubmissionOption, key)) {
            if (ApiSubmissionOption[key as keyof typeof ApiSubmissionOption] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiSubmissionOptionFromJSON(json: any): ApiSubmissionOption {
    return ApiSubmissionOptionFromJSONTyped(json, false);
}

export function ApiSubmissionOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSubmissionOption {
    return json as ApiSubmissionOption;
}

export function ApiSubmissionOptionToJSON(value?: ApiSubmissionOption | null): any {
    return value as any;
}

export function ApiSubmissionOptionToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiSubmissionOption {
    return value as ApiSubmissionOption;
}

