/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiAnswerSet } from './ApiAnswerSet';
import {
    ApiAnswerSetFromJSON,
    ApiAnswerSetFromJSONTyped,
    ApiAnswerSetToJSON,
    ApiAnswerSetToJSONTyped,
} from './ApiAnswerSet';

/**
 * 
 * @export
 * @interface ApiSubmission
 */
export interface ApiSubmission {
    /**
     * 
     * @type {string}
     * @memberof ApiSubmission
     */
    submissionId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiSubmission
     */
    teamId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiSubmission
     */
    memberId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiSubmission
     */
    teamName: string;
    /**
     * 
     * @type {string}
     * @memberof ApiSubmission
     */
    memberName: string;
    /**
     * 
     * @type {number}
     * @memberof ApiSubmission
     */
    timestamp: number;
    /**
     * 
     * @type {Array<ApiAnswerSet>}
     * @memberof ApiSubmission
     */
    answers: Array<ApiAnswerSet>;
}

/**
 * Check if a given object implements the ApiSubmission interface.
 */
export function instanceOfApiSubmission(value: object): value is ApiSubmission {
    if (!('submissionId' in value) || value['submissionId'] === undefined) return false;
    if (!('teamId' in value) || value['teamId'] === undefined) return false;
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    if (!('teamName' in value) || value['teamName'] === undefined) return false;
    if (!('memberName' in value) || value['memberName'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('answers' in value) || value['answers'] === undefined) return false;
    return true;
}

export function ApiSubmissionFromJSON(json: any): ApiSubmission {
    return ApiSubmissionFromJSONTyped(json, false);
}

export function ApiSubmissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSubmission {
    if (json == null) {
        return json;
    }
    return {
        
        'submissionId': json['submissionId'],
        'teamId': json['teamId'],
        'memberId': json['memberId'],
        'teamName': json['teamName'],
        'memberName': json['memberName'],
        'timestamp': json['timestamp'],
        'answers': ((json['answers'] as Array<any>).map(ApiAnswerSetFromJSON)),
    };
}

export function ApiSubmissionToJSON(json: any): ApiSubmission {
    return ApiSubmissionToJSONTyped(json, false);
}

export function ApiSubmissionToJSONTyped(value?: ApiSubmission | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'submissionId': value['submissionId'],
        'teamId': value['teamId'],
        'memberId': value['memberId'],
        'teamName': value['teamName'],
        'memberName': value['memberName'],
        'timestamp': value['timestamp'],
        'answers': ((value['answers'] as Array<any>).map(ApiAnswerSetToJSON)),
    };
}

