/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiScore
 */
export interface ApiScore {
    /**
     * 
     * @type {string}
     * @memberof ApiScore
     */
    teamId: string;
    /**
     * 
     * @type {number}
     * @memberof ApiScore
     */
    score: number;
}

/**
 * Check if a given object implements the ApiScore interface.
 */
export function instanceOfApiScore(value: object): value is ApiScore {
    if (!('teamId' in value) || value['teamId'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    return true;
}

export function ApiScoreFromJSON(json: any): ApiScore {
    return ApiScoreFromJSONTyped(json, false);
}

export function ApiScoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiScore {
    if (json == null) {
        return json;
    }
    return {
        
        'teamId': json['teamId'],
        'score': json['score'],
    };
}

export function ApiScoreToJSON(json: any): ApiScore {
    return ApiScoreToJSONTyped(json, false);
}

export function ApiScoreToJSONTyped(value?: ApiScore | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'teamId': value['teamId'],
        'score': value['score'],
    };
}

