/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiScore } from './ApiScore';
import {
    ApiScoreFromJSON,
    ApiScoreFromJSONTyped,
    ApiScoreToJSON,
    ApiScoreToJSONTyped,
} from './ApiScore';

/**
 * 
 * @export
 * @interface ApiScoreOverview
 */
export interface ApiScoreOverview {
    /**
     * 
     * @type {string}
     * @memberof ApiScoreOverview
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ApiScoreOverview
     */
    taskGroup?: string;
    /**
     * 
     * @type {Array<ApiScore>}
     * @memberof ApiScoreOverview
     */
    scores: Array<ApiScore>;
}

/**
 * Check if a given object implements the ApiScoreOverview interface.
 */
export function instanceOfApiScoreOverview(value: object): value is ApiScoreOverview {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('scores' in value) || value['scores'] === undefined) return false;
    return true;
}

export function ApiScoreOverviewFromJSON(json: any): ApiScoreOverview {
    return ApiScoreOverviewFromJSONTyped(json, false);
}

export function ApiScoreOverviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiScoreOverview {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'taskGroup': json['taskGroup'] == null ? undefined : json['taskGroup'],
        'scores': ((json['scores'] as Array<any>).map(ApiScoreFromJSON)),
    };
}

export function ApiScoreOverviewToJSON(json: any): ApiScoreOverview {
    return ApiScoreOverviewToJSONTyped(json, false);
}

export function ApiScoreOverviewToJSONTyped(value?: ApiScoreOverview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'taskGroup': value['taskGroup'],
        'scores': ((value['scores'] as Array<any>).map(ApiScoreToJSON)),
    };
}

