/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiSubmission } from './ApiSubmission';
import {
    ApiSubmissionFromJSON,
    ApiSubmissionFromJSONTyped,
    ApiSubmissionToJSON,
    ApiSubmissionToJSONTyped,
} from './ApiSubmission';

/**
 * 
 * @export
 * @interface ApiSubmissionInfo
 */
export interface ApiSubmissionInfo {
    /**
     * 
     * @type {string}
     * @memberof ApiSubmissionInfo
     */
    evaluationId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiSubmissionInfo
     */
    taskId: string;
    /**
     * 
     * @type {Array<ApiSubmission>}
     * @memberof ApiSubmissionInfo
     */
    submissions: Array<ApiSubmission>;
}

/**
 * Check if a given object implements the ApiSubmissionInfo interface.
 */
export function instanceOfApiSubmissionInfo(value: object): value is ApiSubmissionInfo {
    if (!('evaluationId' in value) || value['evaluationId'] === undefined) return false;
    if (!('taskId' in value) || value['taskId'] === undefined) return false;
    if (!('submissions' in value) || value['submissions'] === undefined) return false;
    return true;
}

export function ApiSubmissionInfoFromJSON(json: any): ApiSubmissionInfo {
    return ApiSubmissionInfoFromJSONTyped(json, false);
}

export function ApiSubmissionInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSubmissionInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'evaluationId': json['evaluationId'],
        'taskId': json['taskId'],
        'submissions': ((json['submissions'] as Array<any>).map(ApiSubmissionFromJSON)),
    };
}

export function ApiSubmissionInfoToJSON(json: any): ApiSubmissionInfo {
    return ApiSubmissionInfoToJSONTyped(json, false);
}

export function ApiSubmissionInfoToJSONTyped(value?: ApiSubmissionInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'evaluationId': value['evaluationId'],
        'taskId': value['taskId'],
        'submissions': ((value['submissions'] as Array<any>).map(ApiSubmissionToJSON)),
    };
}

