/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiTaskTemplateInfo
 */
export interface ApiTaskTemplateInfo {
    /**
     * 
     * @type {string}
     * @memberof ApiTaskTemplateInfo
     */
    templateId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTaskTemplateInfo
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTaskTemplateInfo
     */
    comment?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTaskTemplateInfo
     */
    taskGroup: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTaskTemplateInfo
     */
    taskType: string;
    /**
     * 
     * @type {number}
     * @memberof ApiTaskTemplateInfo
     */
    duration: number;
}

/**
 * Check if a given object implements the ApiTaskTemplateInfo interface.
 */
export function instanceOfApiTaskTemplateInfo(value: object): value is ApiTaskTemplateInfo {
    if (!('templateId' in value) || value['templateId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('taskGroup' in value) || value['taskGroup'] === undefined) return false;
    if (!('taskType' in value) || value['taskType'] === undefined) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    return true;
}

export function ApiTaskTemplateInfoFromJSON(json: any): ApiTaskTemplateInfo {
    return ApiTaskTemplateInfoFromJSONTyped(json, false);
}

export function ApiTaskTemplateInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTaskTemplateInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'templateId': json['templateId'],
        'name': json['name'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'taskGroup': json['taskGroup'],
        'taskType': json['taskType'],
        'duration': json['duration'],
    };
}

export function ApiTaskTemplateInfoToJSON(json: any): ApiTaskTemplateInfo {
    return ApiTaskTemplateInfoToJSONTyped(json, false);
}

export function ApiTaskTemplateInfoToJSONTyped(value?: ApiTaskTemplateInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'templateId': value['templateId'],
        'name': value['name'],
        'comment': value['comment'],
        'taskGroup': value['taskGroup'],
        'taskType': value['taskType'],
        'duration': value['duration'],
    };
}

