/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApiTemporalUnit = {
    FrameNumber: 'FRAME_NUMBER',
    Seconds: 'SECONDS',
    Milliseconds: 'MILLISECONDS',
    Timecode: 'TIMECODE'
} as const;
export type ApiTemporalUnit = typeof ApiTemporalUnit[keyof typeof ApiTemporalUnit];


export function instanceOfApiTemporalUnit(value: any): boolean {
    for (const key in ApiTemporalUnit) {
        if (Object.prototype.hasOwnProperty.call(ApiTemporalUnit, key)) {
            if (ApiTemporalUnit[key as keyof typeof ApiTemporalUnit] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiTemporalUnitFromJSON(json: any): ApiTemporalUnit {
    return ApiTemporalUnitFromJSONTyped(json, false);
}

export function ApiTemporalUnitFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTemporalUnit {
    return json as ApiTemporalUnit;
}

export function ApiTemporalUnitToJSON(value?: ApiTemporalUnit | null): any {
    return value as any;
}

export function ApiTemporalUnitToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiTemporalUnit {
    return value as ApiTemporalUnit;
}

