/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiTemporalPoint } from './ApiTemporalPoint';
import {
    ApiTemporalPointFromJSON,
    ApiTemporalPointFromJSONTyped,
    ApiTemporalPointToJSON,
    ApiTemporalPointToJSONTyped,
} from './ApiTemporalPoint';

/**
 * 
 * @export
 * @interface ApiTemporalRange
 */
export interface ApiTemporalRange {
    /**
     * 
     * @type {ApiTemporalPoint}
     * @memberof ApiTemporalRange
     */
    start: ApiTemporalPoint;
    /**
     * 
     * @type {ApiTemporalPoint}
     * @memberof ApiTemporalRange
     */
    end: ApiTemporalPoint;
}

/**
 * Check if a given object implements the ApiTemporalRange interface.
 */
export function instanceOfApiTemporalRange(value: object): value is ApiTemporalRange {
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    return true;
}

export function ApiTemporalRangeFromJSON(json: any): ApiTemporalRange {
    return ApiTemporalRangeFromJSONTyped(json, false);
}

export function ApiTemporalRangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTemporalRange {
    if (json == null) {
        return json;
    }
    return {
        
        'start': ApiTemporalPointFromJSON(json['start']),
        'end': ApiTemporalPointFromJSON(json['end']),
    };
}

export function ApiTemporalRangeToJSON(json: any): ApiTemporalRange {
    return ApiTemporalRangeToJSONTyped(json, false);
}

export function ApiTemporalRangeToJSONTyped(value?: ApiTemporalRange | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start': ApiTemporalPointToJSON(value['start']),
        'end': ApiTemporalPointToJSON(value['end']),
    };
}

