/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiHint } from './ApiHint';
import {
    ApiHintFromJSON,
    ApiHintFromJSONTyped,
    ApiHintToJSON,
    ApiHintToJSONTyped,
} from './ApiHint';
import type { ApiTarget } from './ApiTarget';
import {
    ApiTargetFromJSON,
    ApiTargetFromJSONTyped,
    ApiTargetToJSON,
    ApiTargetToJSONTyped,
} from './ApiTarget';

/**
 * 
 * @export
 * @interface ApiTaskTemplate
 */
export interface ApiTaskTemplate {
    /**
     * 
     * @type {string}
     * @memberof ApiTaskTemplate
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTaskTemplate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTaskTemplate
     */
    taskGroup: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTaskTemplate
     */
    taskType: string;
    /**
     * 
     * @type {number}
     * @memberof ApiTaskTemplate
     */
    duration: number;
    /**
     * 
     * @type {string}
     * @memberof ApiTaskTemplate
     */
    collectionId: string;
    /**
     * 
     * @type {Array<ApiTarget>}
     * @memberof ApiTaskTemplate
     */
    targets: Array<ApiTarget>;
    /**
     * 
     * @type {Array<ApiHint>}
     * @memberof ApiTaskTemplate
     */
    hints: Array<ApiHint>;
    /**
     * 
     * @type {string}
     * @memberof ApiTaskTemplate
     */
    comment?: string;
}

/**
 * Check if a given object implements the ApiTaskTemplate interface.
 */
export function instanceOfApiTaskTemplate(value: object): value is ApiTaskTemplate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('taskGroup' in value) || value['taskGroup'] === undefined) return false;
    if (!('taskType' in value) || value['taskType'] === undefined) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('collectionId' in value) || value['collectionId'] === undefined) return false;
    if (!('targets' in value) || value['targets'] === undefined) return false;
    if (!('hints' in value) || value['hints'] === undefined) return false;
    return true;
}

export function ApiTaskTemplateFromJSON(json: any): ApiTaskTemplate {
    return ApiTaskTemplateFromJSONTyped(json, false);
}

export function ApiTaskTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTaskTemplate {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'taskGroup': json['taskGroup'],
        'taskType': json['taskType'],
        'duration': json['duration'],
        'collectionId': json['collectionId'],
        'targets': ((json['targets'] as Array<any>).map(ApiTargetFromJSON)),
        'hints': ((json['hints'] as Array<any>).map(ApiHintFromJSON)),
        'comment': json['comment'] == null ? undefined : json['comment'],
    };
}

export function ApiTaskTemplateToJSON(json: any): ApiTaskTemplate {
    return ApiTaskTemplateToJSONTyped(json, false);
}

export function ApiTaskTemplateToJSONTyped(value?: ApiTaskTemplate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'taskGroup': value['taskGroup'],
        'taskType': value['taskType'],
        'duration': value['duration'],
        'collectionId': value['collectionId'],
        'targets': ((value['targets'] as Array<any>).map(ApiTargetToJSON)),
        'hints': ((value['hints'] as Array<any>).map(ApiHintToJSON)),
        'comment': value['comment'],
    };
}

