/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApiTargetType = {
    Judgement: 'JUDGEMENT',
    JudgementWithVote: 'JUDGEMENT_WITH_VOTE',
    MediaItem: 'MEDIA_ITEM',
    MediaItemTemporalRange: 'MEDIA_ITEM_TEMPORAL_RANGE',
    Text: 'TEXT'
} as const;
export type ApiTargetType = typeof ApiTargetType[keyof typeof ApiTargetType];


export function instanceOfApiTargetType(value: any): boolean {
    for (const key in ApiTargetType) {
        if (Object.prototype.hasOwnProperty.call(ApiTargetType, key)) {
            if (ApiTargetType[key as keyof typeof ApiTargetType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiTargetTypeFromJSON(json: any): ApiTargetType {
    return ApiTargetTypeFromJSONTyped(json, false);
}

export function ApiTargetTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTargetType {
    return json as ApiTargetType;
}

export function ApiTargetTypeToJSON(value?: ApiTargetType | null): any {
    return value as any;
}

export function ApiTargetTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiTargetType {
    return value as ApiTargetType;
}

