/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiHintOption } from './ApiHintOption';
import {
    ApiHintOptionFromJSON,
    ApiHintOptionFromJSONTyped,
    ApiHintOptionToJSON,
    ApiHintOptionToJSONTyped,
} from './ApiHintOption';
import type { ApiTargetOption } from './ApiTargetOption';
import {
    ApiTargetOptionFromJSON,
    ApiTargetOptionFromJSONTyped,
    ApiTargetOptionToJSON,
    ApiTargetOptionToJSONTyped,
} from './ApiTargetOption';
import type { ApiSubmissionOption } from './ApiSubmissionOption';
import {
    ApiSubmissionOptionFromJSON,
    ApiSubmissionOptionFromJSONTyped,
    ApiSubmissionOptionToJSON,
    ApiSubmissionOptionToJSONTyped,
} from './ApiSubmissionOption';
import type { ApiTaskOption } from './ApiTaskOption';
import {
    ApiTaskOptionFromJSON,
    ApiTaskOptionFromJSONTyped,
    ApiTaskOptionToJSON,
    ApiTaskOptionToJSONTyped,
} from './ApiTaskOption';
import type { ApiScoreOption } from './ApiScoreOption';
import {
    ApiScoreOptionFromJSON,
    ApiScoreOptionFromJSONTyped,
    ApiScoreOptionToJSON,
    ApiScoreOptionToJSONTyped,
} from './ApiScoreOption';

/**
 * 
 * @export
 * @interface ApiTaskType
 */
export interface ApiTaskType {
    /**
     * 
     * @type {string}
     * @memberof ApiTaskType
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ApiTaskType
     */
    duration: number;
    /**
     * 
     * @type {ApiTargetOption}
     * @memberof ApiTaskType
     */
    targetOption: ApiTargetOption;
    /**
     * 
     * @type {Array<ApiHintOption>}
     * @memberof ApiTaskType
     */
    hintOptions: Array<ApiHintOption>;
    /**
     * 
     * @type {Array<ApiSubmissionOption>}
     * @memberof ApiTaskType
     */
    submissionOptions: Array<ApiSubmissionOption>;
    /**
     * 
     * @type {Array<ApiTaskOption>}
     * @memberof ApiTaskType
     */
    taskOptions: Array<ApiTaskOption>;
    /**
     * 
     * @type {ApiScoreOption}
     * @memberof ApiTaskType
     */
    scoreOption: ApiScoreOption;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ApiTaskType
     */
    _configuration: { [key: string]: string; };
}



/**
 * Check if a given object implements the ApiTaskType interface.
 */
export function instanceOfApiTaskType(value: object): value is ApiTaskType {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('targetOption' in value) || value['targetOption'] === undefined) return false;
    if (!('hintOptions' in value) || value['hintOptions'] === undefined) return false;
    if (!('submissionOptions' in value) || value['submissionOptions'] === undefined) return false;
    if (!('taskOptions' in value) || value['taskOptions'] === undefined) return false;
    if (!('scoreOption' in value) || value['scoreOption'] === undefined) return false;
    if (!('_configuration' in value) || value['_configuration'] === undefined) return false;
    return true;
}

export function ApiTaskTypeFromJSON(json: any): ApiTaskType {
    return ApiTaskTypeFromJSONTyped(json, false);
}

export function ApiTaskTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTaskType {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'duration': json['duration'],
        'targetOption': ApiTargetOptionFromJSON(json['targetOption']),
        'hintOptions': ((json['hintOptions'] as Array<any>).map(ApiHintOptionFromJSON)),
        'submissionOptions': ((json['submissionOptions'] as Array<any>).map(ApiSubmissionOptionFromJSON)),
        'taskOptions': ((json['taskOptions'] as Array<any>).map(ApiTaskOptionFromJSON)),
        'scoreOption': ApiScoreOptionFromJSON(json['scoreOption']),
        '_configuration': json['configuration'],
    };
}

export function ApiTaskTypeToJSON(json: any): ApiTaskType {
    return ApiTaskTypeToJSONTyped(json, false);
}

export function ApiTaskTypeToJSONTyped(value?: ApiTaskType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'duration': value['duration'],
        'targetOption': ApiTargetOptionToJSON(value['targetOption']),
        'hintOptions': ((value['hintOptions'] as Array<any>).map(ApiHintOptionToJSON)),
        'submissionOptions': ((value['submissionOptions'] as Array<any>).map(ApiSubmissionOptionToJSON)),
        'taskOptions': ((value['taskOptions'] as Array<any>).map(ApiTaskOptionToJSON)),
        'scoreOption': ApiScoreOptionToJSON(value['scoreOption']),
        'configuration': value['_configuration'],
    };
}

