/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApiTaskStatus = {
    NoTask: 'NO_TASK',
    Created: 'CREATED',
    Preparing: 'PREPARING',
    Running: 'RUNNING',
    Ended: 'ENDED',
    Ignored: 'IGNORED'
} as const;
export type ApiTaskStatus = typeof ApiTaskStatus[keyof typeof ApiTaskStatus];


export function instanceOfApiTaskStatus(value: any): boolean {
    for (const key in ApiTaskStatus) {
        if (Object.prototype.hasOwnProperty.call(ApiTaskStatus, key)) {
            if (ApiTaskStatus[key as keyof typeof ApiTaskStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiTaskStatusFromJSON(json: any): ApiTaskStatus {
    return ApiTaskStatusFromJSONTyped(json, false);
}

export function ApiTaskStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTaskStatus {
    return json as ApiTaskStatus;
}

export function ApiTaskStatusToJSON(value?: ApiTaskStatus | null): any {
    return value as any;
}

export function ApiTaskStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiTaskStatus {
    return value as ApiTaskStatus;
}

