/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiTemporalRange } from './ApiTemporalRange';
import {
    ApiTemporalRangeFromJSON,
    ApiTemporalRangeFromJSONTyped,
    ApiTemporalRangeToJSON,
    ApiTemporalRangeToJSONTyped,
} from './ApiTemporalRange';
import type { ApiMediaItem } from './ApiMediaItem';
import {
    ApiMediaItemFromJSON,
    ApiMediaItemFromJSONTyped,
    ApiMediaItemToJSON,
    ApiMediaItemToJSONTyped,
} from './ApiMediaItem';
import type { ApiTargetType } from './ApiTargetType';
import {
    ApiTargetTypeFromJSON,
    ApiTargetTypeFromJSONTyped,
    ApiTargetTypeToJSON,
    ApiTargetTypeToJSONTyped,
} from './ApiTargetType';

/**
 * 
 * @export
 * @interface ApiTarget
 */
export interface ApiTarget {
    /**
     * 
     * @type {ApiTargetType}
     * @memberof ApiTarget
     */
    type: ApiTargetType;
    /**
     * 
     * @type {string}
     * @memberof ApiTarget
     */
    target?: string;
    /**
     * 
     * @type {ApiTemporalRange}
     * @memberof ApiTarget
     */
    range?: ApiTemporalRange;
    /**
     * 
     * @type {ApiMediaItem}
     * @memberof ApiTarget
     */
    item?: ApiMediaItem;
}



/**
 * Check if a given object implements the ApiTarget interface.
 */
export function instanceOfApiTarget(value: object): value is ApiTarget {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ApiTargetFromJSON(json: any): ApiTarget {
    return ApiTargetFromJSONTyped(json, false);
}

export function ApiTargetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTarget {
    if (json == null) {
        return json;
    }
    return {
        
        'type': ApiTargetTypeFromJSON(json['type']),
        'target': json['target'] == null ? undefined : json['target'],
        'range': json['range'] == null ? undefined : ApiTemporalRangeFromJSON(json['range']),
        'item': json['item'] == null ? undefined : ApiMediaItemFromJSON(json['item']),
    };
}

export function ApiTargetToJSON(json: any): ApiTarget {
    return ApiTargetToJSONTyped(json, false);
}

export function ApiTargetToJSONTyped(value?: ApiTarget | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': ApiTargetTypeToJSON(value['type']),
        'target': value['target'],
        'range': ApiTemporalRangeToJSON(value['range']),
        'item': ApiMediaItemToJSON(value['item']),
    };
}

