/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiTaskGroup
 */
export interface ApiTaskGroup {
    /**
     * 
     * @type {string}
     * @memberof ApiTaskGroup
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTaskGroup
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTaskGroup
     */
    type: string;
}

/**
 * Check if a given object implements the ApiTaskGroup interface.
 */
export function instanceOfApiTaskGroup(value: object): value is ApiTaskGroup {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ApiTaskGroupFromJSON(json: any): ApiTaskGroup {
    return ApiTaskGroupFromJSONTyped(json, false);
}

export function ApiTaskGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTaskGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'type': json['type'],
    };
}

export function ApiTaskGroupToJSON(json: any): ApiTaskGroup {
    return ApiTaskGroupToJSONTyped(json, false);
}

export function ApiTaskGroupToJSONTyped(value?: ApiTaskGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': value['type'],
    };
}

