/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApiTargetOption = {
    SingleMediaItem: 'SINGLE_MEDIA_ITEM',
    SingleMediaSegment: 'SINGLE_MEDIA_SEGMENT',
    Judgement: 'JUDGEMENT',
    Vote: 'VOTE',
    Text: 'TEXT'
} as const;
export type ApiTargetOption = typeof ApiTargetOption[keyof typeof ApiTargetOption];


export function instanceOfApiTargetOption(value: any): boolean {
    for (const key in ApiTargetOption) {
        if (Object.prototype.hasOwnProperty.call(ApiTargetOption, key)) {
            if (ApiTargetOption[key as keyof typeof ApiTargetOption] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiTargetOptionFromJSON(json: any): ApiTargetOption {
    return ApiTargetOptionFromJSONTyped(json, false);
}

export function ApiTargetOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTargetOption {
    return json as ApiTargetOption;
}

export function ApiTargetOptionToJSON(value?: ApiTargetOption | null): any {
    return value as any;
}

export function ApiTargetOptionToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiTargetOption {
    return value as ApiTargetOption;
}

