/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiContentElement } from './ApiContentElement';
import {
    ApiContentElementFromJSON,
    ApiContentElementFromJSONTyped,
    ApiContentElementToJSON,
    ApiContentElementToJSONTyped,
} from './ApiContentElement';

/**
 * 
 * @export
 * @interface ApiTargetContent
 */
export interface ApiTargetContent {
    /**
     * 
     * @type {string}
     * @memberof ApiTargetContent
     */
    taskId: string;
    /**
     * 
     * @type {Array<ApiContentElement>}
     * @memberof ApiTargetContent
     */
    sequence: Array<ApiContentElement>;
}

/**
 * Check if a given object implements the ApiTargetContent interface.
 */
export function instanceOfApiTargetContent(value: object): value is ApiTargetContent {
    if (!('taskId' in value) || value['taskId'] === undefined) return false;
    if (!('sequence' in value) || value['sequence'] === undefined) return false;
    return true;
}

export function ApiTargetContentFromJSON(json: any): ApiTargetContent {
    return ApiTargetContentFromJSONTyped(json, false);
}

export function ApiTargetContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTargetContent {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['taskId'],
        'sequence': ((json['sequence'] as Array<any>).map(ApiContentElementFromJSON)),
    };
}

export function ApiTargetContentToJSON(json: any): ApiTargetContent {
    return ApiTargetContentToJSONTyped(json, false);
}

export function ApiTargetContentToJSONTyped(value?: ApiTargetContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'taskId': value['taskId'],
        'sequence': ((value['sequence'] as Array<any>).map(ApiContentElementToJSON)),
    };
}

