/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiTeamGroupValue
 */
export interface ApiTeamGroupValue {
    /**
     * 
     * @type {string}
     * @memberof ApiTeamGroupValue
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ApiTeamGroupValue
     */
    value: number;
}

/**
 * Check if a given object implements the ApiTeamGroupValue interface.
 */
export function instanceOfApiTeamGroupValue(value: object): value is ApiTeamGroupValue {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function ApiTeamGroupValueFromJSON(json: any): ApiTeamGroupValue {
    return ApiTeamGroupValueFromJSONTyped(json, false);
}

export function ApiTeamGroupValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTeamGroupValue {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': json['value'],
    };
}

export function ApiTeamGroupValueToJSON(json: any): ApiTeamGroupValue {
    return ApiTeamGroupValueToJSONTyped(json, false);
}

export function ApiTeamGroupValueToJSONTyped(value?: ApiTeamGroupValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'value': value['value'],
    };
}

