/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiTeamInfo
 */
export interface ApiTeamInfo {
    /**
     * 
     * @type {string}
     * @memberof ApiTeamInfo
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTeamInfo
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTeamInfo
     */
    color: string;
}

/**
 * Check if a given object implements the ApiTeamInfo interface.
 */
export function instanceOfApiTeamInfo(value: object): value is ApiTeamInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('color' in value) || value['color'] === undefined) return false;
    return true;
}

export function ApiTeamInfoFromJSON(json: any): ApiTeamInfo {
    return ApiTeamInfoFromJSONTyped(json, false);
}

export function ApiTeamInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTeamInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'color': json['color'],
    };
}

export function ApiTeamInfoToJSON(json: any): ApiTeamInfo {
    return ApiTeamInfoToJSONTyped(json, false);
}

export function ApiTeamInfoToJSONTyped(value?: ApiTeamInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'color': value['color'],
    };
}

