/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApiTaskOption = {
    HiddenResults: 'HIDDEN_RESULTS',
    MapToSegment: 'MAP_TO_SEGMENT',
    ProlongOnSubmission: 'PROLONG_ON_SUBMISSION'
} as const;
export type ApiTaskOption = typeof ApiTaskOption[keyof typeof ApiTaskOption];


export function instanceOfApiTaskOption(value: any): boolean {
    for (const key in ApiTaskOption) {
        if (Object.prototype.hasOwnProperty.call(ApiTaskOption, key)) {
            if (ApiTaskOption[key as keyof typeof ApiTaskOption] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiTaskOptionFromJSON(json: any): ApiTaskOption {
    return ApiTaskOptionFromJSONTyped(json, false);
}

export function ApiTaskOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTaskOption {
    return json as ApiTaskOption;
}

export function ApiTaskOptionToJSON(value?: ApiTaskOption | null): any {
    return value as any;
}

export function ApiTaskOptionToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiTaskOption {
    return value as ApiTaskOption;
}

