/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApiTeamAggregatorType = {
    Min: 'MIN',
    Max: 'MAX',
    Mean: 'MEAN',
    Last: 'LAST'
} as const;
export type ApiTeamAggregatorType = typeof ApiTeamAggregatorType[keyof typeof ApiTeamAggregatorType];


export function instanceOfApiTeamAggregatorType(value: any): boolean {
    for (const key in ApiTeamAggregatorType) {
        if (Object.prototype.hasOwnProperty.call(ApiTeamAggregatorType, key)) {
            if (ApiTeamAggregatorType[key as keyof typeof ApiTeamAggregatorType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiTeamAggregatorTypeFromJSON(json: any): ApiTeamAggregatorType {
    return ApiTeamAggregatorTypeFromJSONTyped(json, false);
}

export function ApiTeamAggregatorTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTeamAggregatorType {
    return json as ApiTeamAggregatorType;
}

export function ApiTeamAggregatorTypeToJSON(value?: ApiTeamAggregatorType | null): any {
    return value as any;
}

export function ApiTeamAggregatorTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiTeamAggregatorType {
    return value as ApiTeamAggregatorType;
}

