/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiTeam } from './ApiTeam';
import {
    ApiTeamFromJSON,
    ApiTeamFromJSONTyped,
    ApiTeamToJSON,
    ApiTeamToJSONTyped,
} from './ApiTeam';
import type { ApiTeamAggregatorType } from './ApiTeamAggregatorType';
import {
    ApiTeamAggregatorTypeFromJSON,
    ApiTeamAggregatorTypeFromJSONTyped,
    ApiTeamAggregatorTypeToJSON,
    ApiTeamAggregatorTypeToJSONTyped,
} from './ApiTeamAggregatorType';

/**
 * 
 * @export
 * @interface ApiTeamGroup
 */
export interface ApiTeamGroup {
    /**
     * 
     * @type {string}
     * @memberof ApiTeamGroup
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTeamGroup
     */
    name?: string;
    /**
     * 
     * @type {Array<ApiTeam>}
     * @memberof ApiTeamGroup
     */
    teams: Array<ApiTeam>;
    /**
     * 
     * @type {ApiTeamAggregatorType}
     * @memberof ApiTeamGroup
     */
    aggregation: ApiTeamAggregatorType;
}



/**
 * Check if a given object implements the ApiTeamGroup interface.
 */
export function instanceOfApiTeamGroup(value: object): value is ApiTeamGroup {
    if (!('teams' in value) || value['teams'] === undefined) return false;
    if (!('aggregation' in value) || value['aggregation'] === undefined) return false;
    return true;
}

export function ApiTeamGroupFromJSON(json: any): ApiTeamGroup {
    return ApiTeamGroupFromJSONTyped(json, false);
}

export function ApiTeamGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTeamGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'teams': ((json['teams'] as Array<any>).map(ApiTeamFromJSON)),
        'aggregation': ApiTeamAggregatorTypeFromJSON(json['aggregation']),
    };
}

export function ApiTeamGroupToJSON(json: any): ApiTeamGroup {
    return ApiTeamGroupToJSONTyped(json, false);
}

export function ApiTeamGroupToJSONTyped(value?: ApiTeamGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'teams': ((value['teams'] as Array<any>).map(ApiTeamToJSON)),
        'aggregation': ApiTeamAggregatorTypeToJSON(value['aggregation']),
    };
}

