/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiTaskOverview } from './ApiTaskOverview';
import {
    ApiTaskOverviewFromJSON,
    ApiTaskOverviewFromJSONTyped,
    ApiTaskOverviewToJSON,
    ApiTaskOverviewToJSONTyped,
} from './ApiTaskOverview';

/**
 * 
 * @export
 * @interface ApiTeamTaskOverview
 */
export interface ApiTeamTaskOverview {
    /**
     * 
     * @type {string}
     * @memberof ApiTeamTaskOverview
     */
    teamId: string;
    /**
     * 
     * @type {Array<ApiTaskOverview>}
     * @memberof ApiTeamTaskOverview
     */
    tasks: Array<ApiTaskOverview>;
}

/**
 * Check if a given object implements the ApiTeamTaskOverview interface.
 */
export function instanceOfApiTeamTaskOverview(value: object): value is ApiTeamTaskOverview {
    if (!('teamId' in value) || value['teamId'] === undefined) return false;
    if (!('tasks' in value) || value['tasks'] === undefined) return false;
    return true;
}

export function ApiTeamTaskOverviewFromJSON(json: any): ApiTeamTaskOverview {
    return ApiTeamTaskOverviewFromJSONTyped(json, false);
}

export function ApiTeamTaskOverviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTeamTaskOverview {
    if (json == null) {
        return json;
    }
    return {
        
        'teamId': json['teamId'],
        'tasks': ((json['tasks'] as Array<any>).map(ApiTaskOverviewFromJSON)),
    };
}

export function ApiTeamTaskOverviewToJSON(json: any): ApiTeamTaskOverview {
    return ApiTeamTaskOverviewToJSONTyped(json, false);
}

export function ApiTeamTaskOverviewToJSONTyped(value?: ApiTeamTaskOverview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'teamId': value['teamId'],
        'tasks': ((value['tasks'] as Array<any>).map(ApiTaskOverviewToJSON)),
    };
}

