/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiTemporalUnit } from './ApiTemporalUnit';
import {
    ApiTemporalUnitFromJSON,
    ApiTemporalUnitFromJSONTyped,
    ApiTemporalUnitToJSON,
    ApiTemporalUnitToJSONTyped,
} from './ApiTemporalUnit';

/**
 * 
 * @export
 * @interface ApiTemporalPoint
 */
export interface ApiTemporalPoint {
    /**
     * 
     * @type {string}
     * @memberof ApiTemporalPoint
     */
    value: string;
    /**
     * 
     * @type {ApiTemporalUnit}
     * @memberof ApiTemporalPoint
     */
    unit: ApiTemporalUnit;
}



/**
 * Check if a given object implements the ApiTemporalPoint interface.
 */
export function instanceOfApiTemporalPoint(value: object): value is ApiTemporalPoint {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    return true;
}

export function ApiTemporalPointFromJSON(json: any): ApiTemporalPoint {
    return ApiTemporalPointFromJSONTyped(json, false);
}

export function ApiTemporalPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTemporalPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
        'unit': ApiTemporalUnitFromJSON(json['unit']),
    };
}

export function ApiTemporalPointToJSON(json: any): ApiTemporalPoint {
    return ApiTemporalPointToJSONTyped(json, false);
}

export function ApiTemporalPointToJSONTyped(value?: ApiTemporalPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'unit': ApiTemporalUnitToJSON(value['unit']),
    };
}

