/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiUser } from './ApiUser';
import {
    ApiUserFromJSON,
    ApiUserFromJSONTyped,
    ApiUserToJSON,
    ApiUserToJSONTyped,
} from './ApiUser';

/**
 * 
 * @export
 * @interface ApiTeam
 */
export interface ApiTeam {
    /**
     * 
     * @type {string}
     * @memberof ApiTeam
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTeam
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTeam
     */
    color?: string;
    /**
     * 
     * @type {Array<ApiUser>}
     * @memberof ApiTeam
     */
    users: Array<ApiUser>;
    /**
     * 
     * @type {string}
     * @memberof ApiTeam
     */
    logoData?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTeam
     */
    teamId: string;
}

/**
 * Check if a given object implements the ApiTeam interface.
 */
export function instanceOfApiTeam(value: object): value is ApiTeam {
    if (!('users' in value) || value['users'] === undefined) return false;
    if (!('teamId' in value) || value['teamId'] === undefined) return false;
    return true;
}

export function ApiTeamFromJSON(json: any): ApiTeam {
    return ApiTeamFromJSONTyped(json, false);
}

export function ApiTeamFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTeam {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'color': json['color'] == null ? undefined : json['color'],
        'users': ((json['users'] as Array<any>).map(ApiUserFromJSON)),
        'logoData': json['logoData'] == null ? undefined : json['logoData'],
        'teamId': json['teamId'],
    };
}

export function ApiTeamToJSON(json: any): ApiTeam {
    return ApiTeamToJSONTyped(json, false);
}

export function ApiTeamToJSONTyped(value?: ApiTeam | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'color': value['color'],
        'users': ((value['users'] as Array<any>).map(ApiUserToJSON)),
        'logoData': value['logoData'],
        'teamId': value['teamId'],
    };
}

