/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiTaskStatus } from './ApiTaskStatus';
import {
    ApiTaskStatusFromJSON,
    ApiTaskStatusFromJSONTyped,
    ApiTaskStatusToJSON,
    ApiTaskStatusToJSONTyped,
} from './ApiTaskStatus';

/**
 * 
 * @export
 * @interface ApiTaskOverview
 */
export interface ApiTaskOverview {
    /**
     * 
     * @type {string}
     * @memberof ApiTaskOverview
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTaskOverview
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTaskOverview
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTaskOverview
     */
    group: string;
    /**
     * 
     * @type {number}
     * @memberof ApiTaskOverview
     */
    duration: number;
    /**
     * 
     * @type {string}
     * @memberof ApiTaskOverview
     */
    taskId: string;
    /**
     * 
     * @type {ApiTaskStatus}
     * @memberof ApiTaskOverview
     */
    status: ApiTaskStatus;
    /**
     * 
     * @type {number}
     * @memberof ApiTaskOverview
     */
    started?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiTaskOverview
     */
    ended?: number;
}



/**
 * Check if a given object implements the ApiTaskOverview interface.
 */
export function instanceOfApiTaskOverview(value: object): value is ApiTaskOverview {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('group' in value) || value['group'] === undefined) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('taskId' in value) || value['taskId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ApiTaskOverviewFromJSON(json: any): ApiTaskOverview {
    return ApiTaskOverviewFromJSONTyped(json, false);
}

export function ApiTaskOverviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTaskOverview {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'type': json['type'],
        'group': json['group'],
        'duration': json['duration'],
        'taskId': json['taskId'],
        'status': ApiTaskStatusFromJSON(json['status']),
        'started': json['started'] == null ? undefined : json['started'],
        'ended': json['ended'] == null ? undefined : json['ended'],
    };
}

export function ApiTaskOverviewToJSON(json: any): ApiTaskOverview {
    return ApiTaskOverviewToJSONTyped(json, false);
}

export function ApiTaskOverviewToJSONTyped(value?: ApiTaskOverview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': value['type'],
        'group': value['group'],
        'duration': value['duration'],
        'taskId': value['taskId'],
        'status': ApiTaskStatusToJSON(value['status']),
        'started': value['started'],
        'ended': value['ended'],
    };
}

