/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiSubmission } from './ApiSubmission';
import {
    ApiSubmissionFromJSON,
    ApiSubmissionFromJSONTyped,
    ApiSubmissionToJSON,
    ApiSubmissionToJSONTyped,
} from './ApiSubmission';

/**
 * 
 * @export
 * @interface ApiTask
 */
export interface ApiTask {
    /**
     * 
     * @type {string}
     * @memberof ApiTask
     */
    taskId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTask
     */
    templateId: string;
    /**
     * 
     * @type {number}
     * @memberof ApiTask
     */
    started?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiTask
     */
    ended?: number;
    /**
     * 
     * @type {Array<ApiSubmission>}
     * @memberof ApiTask
     */
    submissions: Array<ApiSubmission>;
}

/**
 * Check if a given object implements the ApiTask interface.
 */
export function instanceOfApiTask(value: object): value is ApiTask {
    if (!('taskId' in value) || value['taskId'] === undefined) return false;
    if (!('templateId' in value) || value['templateId'] === undefined) return false;
    if (!('submissions' in value) || value['submissions'] === undefined) return false;
    return true;
}

export function ApiTaskFromJSON(json: any): ApiTask {
    return ApiTaskFromJSONTyped(json, false);
}

export function ApiTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTask {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['taskId'],
        'templateId': json['templateId'],
        'started': json['started'] == null ? undefined : json['started'],
        'ended': json['ended'] == null ? undefined : json['ended'],
        'submissions': ((json['submissions'] as Array<any>).map(ApiSubmissionFromJSON)),
    };
}

export function ApiTaskToJSON(json: any): ApiTask {
    return ApiTaskToJSONTyped(json, false);
}

export function ApiTaskToJSONTyped(value?: ApiTask | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'taskId': value['taskId'],
        'templateId': value['templateId'],
        'started': value['started'],
        'ended': value['ended'],
        'submissions': ((value['submissions'] as Array<any>).map(ApiSubmissionToJSON)),
    };
}

