/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiRole } from './ApiRole';
import {
    ApiRoleFromJSON,
    ApiRoleFromJSONTyped,
    ApiRoleToJSON,
    ApiRoleToJSONTyped,
} from './ApiRole';

/**
 * 
 * @export
 * @interface ApiUserRequest
 */
export interface ApiUserRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiUserRequest
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof ApiUserRequest
     */
    password?: string;
    /**
     * 
     * @type {ApiRole}
     * @memberof ApiUserRequest
     */
    role?: ApiRole;
}



/**
 * Check if a given object implements the ApiUserRequest interface.
 */
export function instanceOfApiUserRequest(value: object): value is ApiUserRequest {
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function ApiUserRequestFromJSON(json: any): ApiUserRequest {
    return ApiUserRequestFromJSONTyped(json, false);
}

export function ApiUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'] == null ? undefined : json['password'],
        'role': json['role'] == null ? undefined : ApiRoleFromJSON(json['role']),
    };
}

export function ApiUserRequestToJSON(json: any): ApiUserRequest {
    return ApiUserRequestToJSONTyped(json, false);
}

export function ApiUserRequestToJSONTyped(value?: ApiUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
        'role': ApiRoleToJSON(value['role']),
    };
}

