/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiRole } from './ApiRole';
import {
    ApiRoleFromJSON,
    ApiRoleFromJSONTyped,
    ApiRoleToJSON,
    ApiRoleToJSONTyped,
} from './ApiRole';

/**
 * 
 * @export
 * @interface ApiUser
 */
export interface ApiUser {
    /**
     * 
     * @type {string}
     * @memberof ApiUser
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiUser
     */
    username?: string;
    /**
     * 
     * @type {ApiRole}
     * @memberof ApiUser
     */
    role?: ApiRole;
    /**
     * 
     * @type {string}
     * @memberof ApiUser
     */
    sessionId?: string;
}



/**
 * Check if a given object implements the ApiUser interface.
 */
export function instanceOfApiUser(value: object): value is ApiUser {
    return true;
}

export function ApiUserFromJSON(json: any): ApiUser {
    return ApiUserFromJSONTyped(json, false);
}

export function ApiUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'username': json['username'] == null ? undefined : json['username'],
        'role': json['role'] == null ? undefined : ApiRoleFromJSON(json['role']),
        'sessionId': json['sessionId'] == null ? undefined : json['sessionId'],
    };
}

export function ApiUserToJSON(json: any): ApiUser {
    return ApiUserToJSONTyped(json, false);
}

export function ApiUserToJSONTyped(value?: ApiUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'role': ApiRoleToJSON(value['role']),
        'sessionId': value['sessionId'],
    };
}

