/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApiVerdictStatus = {
    Correct: 'CORRECT',
    Wrong: 'WRONG',
    Indeterminate: 'INDETERMINATE',
    Undecidable: 'UNDECIDABLE'
} as const;
export type ApiVerdictStatus = typeof ApiVerdictStatus[keyof typeof ApiVerdictStatus];


export function instanceOfApiVerdictStatus(value: any): boolean {
    for (const key in ApiVerdictStatus) {
        if (Object.prototype.hasOwnProperty.call(ApiVerdictStatus, key)) {
            if (ApiVerdictStatus[key as keyof typeof ApiVerdictStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiVerdictStatusFromJSON(json: any): ApiVerdictStatus {
    return ApiVerdictStatusFromJSONTyped(json, false);
}

export function ApiVerdictStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVerdictStatus {
    return json as ApiVerdictStatus;
}

export function ApiVerdictStatusToJSON(value?: ApiVerdictStatus | null): any {
    return value as any;
}

export function ApiVerdictStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiVerdictStatus {
    return value as ApiVerdictStatus;
}

