/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiViewerInfo
 */
export interface ApiViewerInfo {
    /**
     * 
     * @type {string}
     * @memberof ApiViewerInfo
     */
    viewersId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiViewerInfo
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof ApiViewerInfo
     */
    host: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiViewerInfo
     */
    ready: boolean;
}

/**
 * Check if a given object implements the ApiViewerInfo interface.
 */
export function instanceOfApiViewerInfo(value: object): value is ApiViewerInfo {
    if (!('viewersId' in value) || value['viewersId'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('host' in value) || value['host'] === undefined) return false;
    if (!('ready' in value) || value['ready'] === undefined) return false;
    return true;
}

export function ApiViewerInfoFromJSON(json: any): ApiViewerInfo {
    return ApiViewerInfoFromJSONTyped(json, false);
}

export function ApiViewerInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiViewerInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'viewersId': json['viewersId'],
        'username': json['username'],
        'host': json['host'],
        'ready': json['ready'],
    };
}

export function ApiViewerInfoToJSON(json: any): ApiViewerInfo {
    return ApiViewerInfoToJSONTyped(json, false);
}

export function ApiViewerInfoToJSONTyped(value?: ApiViewerInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'viewersId': value['viewersId'],
        'username': value['username'],
        'host': value['host'],
        'ready': value['ready'],
    };
}

