/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiVerdictStatus } from './ApiVerdictStatus';
import {
    ApiVerdictStatusFromJSON,
    ApiVerdictStatusFromJSONTyped,
    ApiVerdictStatusToJSON,
    ApiVerdictStatusToJSONTyped,
} from './ApiVerdictStatus';

/**
 * 
 * @export
 * @interface ApiVote
 */
export interface ApiVote {
    /**
     * 
     * @type {ApiVerdictStatus}
     * @memberof ApiVote
     */
    verdict: ApiVerdictStatus;
}



/**
 * Check if a given object implements the ApiVote interface.
 */
export function instanceOfApiVote(value: object): value is ApiVote {
    if (!('verdict' in value) || value['verdict'] === undefined) return false;
    return true;
}

export function ApiVoteFromJSON(json: any): ApiVote {
    return ApiVoteFromJSONTyped(json, false);
}

export function ApiVoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVote {
    if (json == null) {
        return json;
    }
    return {
        
        'verdict': ApiVerdictStatusFromJSON(json['verdict']),
    };
}

export function ApiVoteToJSON(json: any): ApiVote {
    return ApiVoteToJSONTyped(json, false);
}

export function ApiVoteToJSONTyped(value?: ApiVote | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verdict': ApiVerdictStatusToJSON(value['verdict']),
    };
}

