/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrentTime
 */
export interface CurrentTime {
    /**
     * 
     * @type {number}
     * @memberof CurrentTime
     */
    timeStamp: number;
}

/**
 * Check if a given object implements the CurrentTime interface.
 */
export function instanceOfCurrentTime(value: object): value is CurrentTime {
    if (!('timeStamp' in value) || value['timeStamp'] === undefined) return false;
    return true;
}

export function CurrentTimeFromJSON(json: any): CurrentTime {
    return CurrentTimeFromJSONTyped(json, false);
}

export function CurrentTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentTime {
    if (json == null) {
        return json;
    }
    return {
        
        'timeStamp': json['timeStamp'],
    };
}

export function CurrentTimeToJSON(json: any): CurrentTime {
    return CurrentTimeToJSONTyped(json, false);
}

export function CurrentTimeToJSONTyped(value?: CurrentTime | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timeStamp': value['timeStamp'],
    };
}

