/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DresInfo
 */
export interface DresInfo {
    /**
     * 
     * @type {string}
     * @memberof DresInfo
     */
    version: string;
    /**
     * 
     * @type {number}
     * @memberof DresInfo
     */
    startTime: number;
    /**
     * 
     * @type {number}
     * @memberof DresInfo
     */
    uptime: number;
    /**
     * 
     * @type {string}
     * @memberof DresInfo
     */
    os?: string;
    /**
     * 
     * @type {string}
     * @memberof DresInfo
     */
    jvm?: string;
    /**
     * 
     * @type {string}
     * @memberof DresInfo
     */
    args?: string;
    /**
     * 
     * @type {number}
     * @memberof DresInfo
     */
    cores?: number;
    /**
     * 
     * @type {number}
     * @memberof DresInfo
     */
    freeMemory?: number;
    /**
     * 
     * @type {number}
     * @memberof DresInfo
     */
    totalMemory?: number;
    /**
     * 
     * @type {number}
     * @memberof DresInfo
     */
    load?: number;
    /**
     * 
     * @type {number}
     * @memberof DresInfo
     */
    availableSeverThreads?: number;
}

/**
 * Check if a given object implements the DresInfo interface.
 */
export function instanceOfDresInfo(value: object): value is DresInfo {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('uptime' in value) || value['uptime'] === undefined) return false;
    return true;
}

export function DresInfoFromJSON(json: any): DresInfo {
    return DresInfoFromJSONTyped(json, false);
}

export function DresInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DresInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'],
        'startTime': json['startTime'],
        'uptime': json['uptime'],
        'os': json['os'] == null ? undefined : json['os'],
        'jvm': json['jvm'] == null ? undefined : json['jvm'],
        'args': json['args'] == null ? undefined : json['args'],
        'cores': json['cores'] == null ? undefined : json['cores'],
        'freeMemory': json['freeMemory'] == null ? undefined : json['freeMemory'],
        'totalMemory': json['totalMemory'] == null ? undefined : json['totalMemory'],
        'load': json['load'] == null ? undefined : json['load'],
        'availableSeverThreads': json['availableSeverThreads'] == null ? undefined : json['availableSeverThreads'],
    };
}

export function DresInfoToJSON(json: any): DresInfo {
    return DresInfoToJSONTyped(json, false);
}

export function DresInfoToJSONTyped(value?: DresInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'startTime': value['startTime'],
        'uptime': value['uptime'],
        'os': value['os'],
        'jvm': value['jvm'],
        'args': value['args'],
        'cores': value['cores'],
        'freeMemory': value['freeMemory'],
        'totalMemory': value['totalMemory'],
        'load': value['load'],
        'availableSeverThreads': value['availableSeverThreads'],
    };
}

