/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorStatus
 */
export interface ErrorStatus {
    /**
     * 
     * @type {boolean}
     * @memberof ErrorStatus
     */
    status: boolean;
    /**
     * 
     * @type {string}
     * @memberof ErrorStatus
     */
    description: string;
}

/**
 * Check if a given object implements the ErrorStatus interface.
 */
export function instanceOfErrorStatus(value: object): value is ErrorStatus {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function ErrorStatusFromJSON(json: any): ErrorStatus {
    return ErrorStatusFromJSONTyped(json, false);
}

export function ErrorStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'description': json['description'],
    };
}

export function ErrorStatusToJSON(json: any): ErrorStatus {
    return ErrorStatusToJSONTyped(json, false);
}

export function ErrorStatusToJSONTyped(value?: ErrorStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'description': value['description'],
    };
}

