/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueryEventCategory } from './QueryEventCategory';
import {
    QueryEventCategoryFromJSON,
    QueryEventCategoryFromJSONTyped,
    QueryEventCategoryToJSON,
    QueryEventCategoryToJSONTyped,
} from './QueryEventCategory';

/**
 * 
 * @export
 * @interface QueryEvent
 */
export interface QueryEvent {
    /**
     * 
     * @type {number}
     * @memberof QueryEvent
     */
    timestamp: number;
    /**
     * 
     * @type {QueryEventCategory}
     * @memberof QueryEvent
     */
    category: QueryEventCategory;
    /**
     * 
     * @type {string}
     * @memberof QueryEvent
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof QueryEvent
     */
    value: string;
}



/**
 * Check if a given object implements the QueryEvent interface.
 */
export function instanceOfQueryEvent(value: object): value is QueryEvent {
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function QueryEventFromJSON(json: any): QueryEvent {
    return QueryEventFromJSONTyped(json, false);
}

export function QueryEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'],
        'category': QueryEventCategoryFromJSON(json['category']),
        'type': json['type'],
        'value': json['value'],
    };
}

export function QueryEventToJSON(json: any): QueryEvent {
    return QueryEventToJSONTyped(json, false);
}

export function QueryEventToJSONTyped(value?: QueryEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'],
        'category': QueryEventCategoryToJSON(value['category']),
        'type': value['type'],
        'value': value['value'],
    };
}

