/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueryEvent } from './QueryEvent';
import {
    QueryEventFromJSON,
    QueryEventFromJSONTyped,
    QueryEventToJSON,
    QueryEventToJSONTyped,
} from './QueryEvent';

/**
 * 
 * @export
 * @interface QueryEventLog
 */
export interface QueryEventLog {
    /**
     * 
     * @type {number}
     * @memberof QueryEventLog
     */
    timestamp: number;
    /**
     * 
     * @type {Array<QueryEvent>}
     * @memberof QueryEventLog
     */
    events: Array<QueryEvent>;
}

/**
 * Check if a given object implements the QueryEventLog interface.
 */
export function instanceOfQueryEventLog(value: object): value is QueryEventLog {
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function QueryEventLogFromJSON(json: any): QueryEventLog {
    return QueryEventLogFromJSONTyped(json, false);
}

export function QueryEventLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryEventLog {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'],
        'events': ((json['events'] as Array<any>).map(QueryEventFromJSON)),
    };
}

export function QueryEventLogToJSON(json: any): QueryEventLog {
    return QueryEventLogToJSONTyped(json, false);
}

export function QueryEventLogToJSONTyped(value?: QueryEventLog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'],
        'events': ((value['events'] as Array<any>).map(QueryEventToJSON)),
    };
}

