/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RankedAnswer } from './RankedAnswer';
import {
    RankedAnswerFromJSON,
    RankedAnswerFromJSONTyped,
    RankedAnswerToJSON,
    RankedAnswerToJSONTyped,
} from './RankedAnswer';
import type { QueryEvent } from './QueryEvent';
import {
    QueryEventFromJSON,
    QueryEventFromJSONTyped,
    QueryEventToJSON,
    QueryEventToJSONTyped,
} from './QueryEvent';

/**
 * 
 * @export
 * @interface QueryResultLog
 */
export interface QueryResultLog {
    /**
     * 
     * @type {number}
     * @memberof QueryResultLog
     */
    timestamp: number;
    /**
     * 
     * @type {string}
     * @memberof QueryResultLog
     */
    sortType: string;
    /**
     * 
     * @type {string}
     * @memberof QueryResultLog
     */
    resultSetAvailability: string;
    /**
     * 
     * @type {Array<RankedAnswer>}
     * @memberof QueryResultLog
     */
    results: Array<RankedAnswer>;
    /**
     * 
     * @type {Array<QueryEvent>}
     * @memberof QueryResultLog
     */
    events: Array<QueryEvent>;
}

/**
 * Check if a given object implements the QueryResultLog interface.
 */
export function instanceOfQueryResultLog(value: object): value is QueryResultLog {
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('sortType' in value) || value['sortType'] === undefined) return false;
    if (!('resultSetAvailability' in value) || value['resultSetAvailability'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function QueryResultLogFromJSON(json: any): QueryResultLog {
    return QueryResultLogFromJSONTyped(json, false);
}

export function QueryResultLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryResultLog {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'],
        'sortType': json['sortType'],
        'resultSetAvailability': json['resultSetAvailability'],
        'results': ((json['results'] as Array<any>).map(RankedAnswerFromJSON)),
        'events': ((json['events'] as Array<any>).map(QueryEventFromJSON)),
    };
}

export function QueryResultLogToJSON(json: any): QueryResultLog {
    return QueryResultLogToJSONTyped(json, false);
}

export function QueryResultLogToJSONTyped(value?: QueryResultLog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'],
        'sortType': value['sortType'],
        'resultSetAvailability': value['resultSetAvailability'],
        'results': ((value['results'] as Array<any>).map(RankedAnswerToJSON)),
        'events': ((value['events'] as Array<any>).map(QueryEventToJSON)),
    };
}

