/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const QueryEventCategory = {
    Text: 'TEXT',
    Image: 'IMAGE',
    Sketch: 'SKETCH',
    Filter: 'FILTER',
    Browsing: 'BROWSING',
    Cooperation: 'COOPERATION',
    Other: 'OTHER'
} as const;
export type QueryEventCategory = typeof QueryEventCategory[keyof typeof QueryEventCategory];


export function instanceOfQueryEventCategory(value: any): boolean {
    for (const key in QueryEventCategory) {
        if (Object.prototype.hasOwnProperty.call(QueryEventCategory, key)) {
            if (QueryEventCategory[key as keyof typeof QueryEventCategory] === value) {
                return true;
            }
        }
    }
    return false;
}

export function QueryEventCategoryFromJSON(json: any): QueryEventCategory {
    return QueryEventCategoryFromJSONTyped(json, false);
}

export function QueryEventCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryEventCategory {
    return json as QueryEventCategory;
}

export function QueryEventCategoryToJSON(value?: QueryEventCategory | null): any {
    return value as any;
}

export function QueryEventCategoryToJSONTyped(value: any, ignoreDiscriminator: boolean): QueryEventCategory {
    return value as QueryEventCategory;
}

