/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiClientAnswer } from './ApiClientAnswer';
import {
    ApiClientAnswerFromJSON,
    ApiClientAnswerFromJSONTyped,
    ApiClientAnswerToJSON,
    ApiClientAnswerToJSONTyped,
} from './ApiClientAnswer';

/**
 * 
 * @export
 * @interface RankedAnswer
 */
export interface RankedAnswer {
    /**
     * 
     * @type {ApiClientAnswer}
     * @memberof RankedAnswer
     */
    answer: ApiClientAnswer;
    /**
     * 
     * @type {number}
     * @memberof RankedAnswer
     */
    rank?: number;
}

/**
 * Check if a given object implements the RankedAnswer interface.
 */
export function instanceOfRankedAnswer(value: object): value is RankedAnswer {
    if (!('answer' in value) || value['answer'] === undefined) return false;
    return true;
}

export function RankedAnswerFromJSON(json: any): RankedAnswer {
    return RankedAnswerFromJSONTyped(json, false);
}

export function RankedAnswerFromJSONTyped(json: any, ignoreDiscriminator: boolean): RankedAnswer {
    if (json == null) {
        return json;
    }
    return {
        
        'answer': ApiClientAnswerFromJSON(json['answer']),
        'rank': json['rank'] == null ? undefined : json['rank'],
    };
}

export function RankedAnswerToJSON(json: any): RankedAnswer {
    return RankedAnswerToJSONTyped(json, false);
}

export function RankedAnswerToJSONTyped(value?: RankedAnswer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'answer': ApiClientAnswerToJSON(value['answer']),
        'rank': value['rank'],
    };
}

