/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RunManagerStatus = {
    Created: 'CREATED',
    Active: 'ACTIVE',
    Terminated: 'TERMINATED'
} as const;
export type RunManagerStatus = typeof RunManagerStatus[keyof typeof RunManagerStatus];


export function instanceOfRunManagerStatus(value: any): boolean {
    for (const key in RunManagerStatus) {
        if (Object.prototype.hasOwnProperty.call(RunManagerStatus, key)) {
            if (RunManagerStatus[key as keyof typeof RunManagerStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RunManagerStatusFromJSON(json: any): RunManagerStatus {
    return RunManagerStatusFromJSONTyped(json, false);
}

export function RunManagerStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunManagerStatus {
    return json as RunManagerStatus;
}

export function RunManagerStatusToJSON(value?: RunManagerStatus | null): any {
    return value as any;
}

export function RunManagerStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): RunManagerStatus {
    return value as RunManagerStatus;
}

