/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SuccessStatus
 */
export interface SuccessStatus {
    /**
     * 
     * @type {boolean}
     * @memberof SuccessStatus
     */
    status: boolean;
    /**
     * 
     * @type {string}
     * @memberof SuccessStatus
     */
    description: string;
}

/**
 * Check if a given object implements the SuccessStatus interface.
 */
export function instanceOfSuccessStatus(value: object): value is SuccessStatus {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function SuccessStatusFromJSON(json: any): SuccessStatus {
    return SuccessStatusFromJSONTyped(json, false);
}

export function SuccessStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'description': json['description'],
    };
}

export function SuccessStatusToJSON(json: any): SuccessStatus {
    return SuccessStatusToJSONTyped(json, false);
}

export function SuccessStatusToJSONTyped(value?: SuccessStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'description': value['description'],
    };
}

