/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiVerdictStatus } from './ApiVerdictStatus';
import {
    ApiVerdictStatusFromJSON,
    ApiVerdictStatusFromJSONTyped,
    ApiVerdictStatusToJSON,
    ApiVerdictStatusToJSONTyped,
} from './ApiVerdictStatus';

/**
 * 
 * @export
 * @interface SuccessfulSubmissionsStatus
 */
export interface SuccessfulSubmissionsStatus {
    /**
     * 
     * @type {boolean}
     * @memberof SuccessfulSubmissionsStatus
     */
    status: boolean;
    /**
     * 
     * @type {ApiVerdictStatus}
     * @memberof SuccessfulSubmissionsStatus
     */
    submission: ApiVerdictStatus;
    /**
     * 
     * @type {string}
     * @memberof SuccessfulSubmissionsStatus
     */
    description: string;
}



/**
 * Check if a given object implements the SuccessfulSubmissionsStatus interface.
 */
export function instanceOfSuccessfulSubmissionsStatus(value: object): value is SuccessfulSubmissionsStatus {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('submission' in value) || value['submission'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function SuccessfulSubmissionsStatusFromJSON(json: any): SuccessfulSubmissionsStatus {
    return SuccessfulSubmissionsStatusFromJSONTyped(json, false);
}

export function SuccessfulSubmissionsStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessfulSubmissionsStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'submission': ApiVerdictStatusFromJSON(json['submission']),
        'description': json['description'],
    };
}

export function SuccessfulSubmissionsStatusToJSON(json: any): SuccessfulSubmissionsStatus {
    return SuccessfulSubmissionsStatusToJSONTyped(json, false);
}

export function SuccessfulSubmissionsStatusToJSONTyped(value?: SuccessfulSubmissionsStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'submission': ApiVerdictStatusToJSON(value['submission']),
        'description': value['description'],
    };
}

