/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemporalRange
 */
export interface TemporalRange {
    /**
     * 
     * @type {object}
     * @memberof TemporalRange
     */
    start: object;
    /**
     * 
     * @type {object}
     * @memberof TemporalRange
     */
    end: object;
    /**
     * 
     * @type {number}
     * @memberof TemporalRange
     */
    center: number;
}

/**
 * Check if a given object implements the TemporalRange interface.
 */
export function instanceOfTemporalRange(value: object): value is TemporalRange {
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('center' in value) || value['center'] === undefined) return false;
    return true;
}

export function TemporalRangeFromJSON(json: any): TemporalRange {
    return TemporalRangeFromJSONTyped(json, false);
}

export function TemporalRangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemporalRange {
    if (json == null) {
        return json;
    }
    return {
        
        'start': json['start'],
        'end': json['end'],
        'center': json['center'],
    };
}

export function TemporalRangeToJSON(json: any): TemporalRange {
    return TemporalRangeToJSONTyped(json, false);
}

export function TemporalRangeToJSONTyped(value?: TemporalRange | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start': value['start'],
        'end': value['end'],
        'center': value['center'],
    };
}

