/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiClientEvaluationInfo,
  ApiClientTaskTemplateInfo,
  ErrorStatus,
} from '../models/index';
import {
    ApiClientEvaluationInfoFromJSON,
    ApiClientEvaluationInfoToJSON,
    ApiClientTaskTemplateInfoFromJSON,
    ApiClientTaskTemplateInfoToJSON,
    ErrorStatusFromJSON,
    ErrorStatusToJSON,
} from '../models/index';

export interface GetApiV2ClientEvaluationCurrentTaskByEvaluationIdRequest {
    evaluationId: string;
    session?: string;
}

export interface GetApiV2ClientEvaluationListRequest {
    session?: string;
}

/**
 * 
 */
export class EvaluationClientApi extends runtime.BaseAPI {

    /**
     * Creates request options for getApiV2ClientEvaluationCurrentTaskByEvaluationId without sending the request
     */
    async getApiV2ClientEvaluationCurrentTaskByEvaluationIdRequestOpts(requestParameters: GetApiV2ClientEvaluationCurrentTaskByEvaluationIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['evaluationId'] == null) {
            throw new runtime.RequiredError(
                'evaluationId',
                'Required parameter "evaluationId" was null or undefined when calling getApiV2ClientEvaluationCurrentTaskByEvaluationId().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['session'] != null) {
            queryParameters['session'] = requestParameters['session'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v2/client/evaluation/currentTask/{evaluationId}`;
        urlPath = urlPath.replace(`{${"evaluationId"}}`, encodeURIComponent(String(requestParameters['evaluationId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns an overview of the currently active task for a run.
     */
    async getApiV2ClientEvaluationCurrentTaskByEvaluationIdRaw(requestParameters: GetApiV2ClientEvaluationCurrentTaskByEvaluationIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiClientTaskTemplateInfo>> {
        const requestOptions = await this.getApiV2ClientEvaluationCurrentTaskByEvaluationIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiClientTaskTemplateInfoFromJSON(jsonValue));
    }

    /**
     * Returns an overview of the currently active task for a run.
     */
    async getApiV2ClientEvaluationCurrentTaskByEvaluationId(requestParameters: GetApiV2ClientEvaluationCurrentTaskByEvaluationIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiClientTaskTemplateInfo> {
        const response = await this.getApiV2ClientEvaluationCurrentTaskByEvaluationIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getApiV2ClientEvaluationList without sending the request
     */
    async getApiV2ClientEvaluationListRequestOpts(requestParameters: GetApiV2ClientEvaluationListRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['session'] != null) {
            queryParameters['session'] = requestParameters['session'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v2/client/evaluation/list`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lists an overview of all evaluation runs visible to the current client.
     */
    async getApiV2ClientEvaluationListRaw(requestParameters: GetApiV2ClientEvaluationListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiClientEvaluationInfo>>> {
        const requestOptions = await this.getApiV2ClientEvaluationListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiClientEvaluationInfoFromJSON));
    }

    /**
     * Lists an overview of all evaluation runs visible to the current client.
     */
    async getApiV2ClientEvaluationList(requestParameters: GetApiV2ClientEvaluationListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiClientEvaluationInfo>> {
        const response = await this.getApiV2ClientEvaluationListRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
