/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiEvaluationInfo,
  ApiEvaluationState,
  ErrorStatus,
} from '../models/index';
import {
    ApiEvaluationInfoFromJSON,
    ApiEvaluationInfoToJSON,
    ApiEvaluationStateFromJSON,
    ApiEvaluationStateToJSON,
    ErrorStatusFromJSON,
    ErrorStatusToJSON,
} from '../models/index';

export interface GetApiV2EvaluationByEvaluationIdInfoRequest {
    evaluationId: string;
}

export interface GetApiV2EvaluationByEvaluationIdStateRequest {
    evaluationId: string;
}

/**
 * 
 */
export class EvaluationApi extends runtime.BaseAPI {

    /**
     * Creates request options for getApiV2EvaluationByEvaluationIdInfo without sending the request
     */
    async getApiV2EvaluationByEvaluationIdInfoRequestOpts(requestParameters: GetApiV2EvaluationByEvaluationIdInfoRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['evaluationId'] == null) {
            throw new runtime.RequiredError(
                'evaluationId',
                'Required parameter "evaluationId" was null or undefined when calling getApiV2EvaluationByEvaluationIdInfo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v2/evaluation/{evaluationId}/info`;
        urlPath = urlPath.replace(`{${"evaluationId"}}`, encodeURIComponent(String(requestParameters['evaluationId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns basic information about a specific evaluation.
     */
    async getApiV2EvaluationByEvaluationIdInfoRaw(requestParameters: GetApiV2EvaluationByEvaluationIdInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiEvaluationInfo>> {
        const requestOptions = await this.getApiV2EvaluationByEvaluationIdInfoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiEvaluationInfoFromJSON(jsonValue));
    }

    /**
     * Returns basic information about a specific evaluation.
     */
    async getApiV2EvaluationByEvaluationIdInfo(requestParameters: GetApiV2EvaluationByEvaluationIdInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiEvaluationInfo> {
        const response = await this.getApiV2EvaluationByEvaluationIdInfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getApiV2EvaluationByEvaluationIdState without sending the request
     */
    async getApiV2EvaluationByEvaluationIdStateRequestOpts(requestParameters: GetApiV2EvaluationByEvaluationIdStateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['evaluationId'] == null) {
            throw new runtime.RequiredError(
                'evaluationId',
                'Required parameter "evaluationId" was null or undefined when calling getApiV2EvaluationByEvaluationIdState().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v2/evaluation/{evaluationId}/state`;
        urlPath = urlPath.replace(`{${"evaluationId"}}`, encodeURIComponent(String(requestParameters['evaluationId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the state of a specific evaluation.
     */
    async getApiV2EvaluationByEvaluationIdStateRaw(requestParameters: GetApiV2EvaluationByEvaluationIdStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiEvaluationState>> {
        const requestOptions = await this.getApiV2EvaluationByEvaluationIdStateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiEvaluationStateFromJSON(jsonValue));
    }

    /**
     * Returns the state of a specific evaluation.
     */
    async getApiV2EvaluationByEvaluationIdState(requestParameters: GetApiV2EvaluationByEvaluationIdStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiEvaluationState> {
        const response = await this.getApiV2EvaluationByEvaluationIdStateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getApiV2EvaluationInfoList without sending the request
     */
    async getApiV2EvaluationInfoListRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v2/evaluation/info/list`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lists an overview of all evaluations visible to the current user.
     */
    async getApiV2EvaluationInfoListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiEvaluationInfo>>> {
        const requestOptions = await this.getApiV2EvaluationInfoListRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiEvaluationInfoFromJSON));
    }

    /**
     * Lists an overview of all evaluations visible to the current user.
     */
    async getApiV2EvaluationInfoList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiEvaluationInfo>> {
        const response = await this.getApiV2EvaluationInfoListRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getApiV2EvaluationStateList without sending the request
     */
    async getApiV2EvaluationStateListRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v2/evaluation/state/list`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lists an overview of all evaluation visible to the current user.
     */
    async getApiV2EvaluationStateListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiEvaluationState>>> {
        const requestOptions = await this.getApiV2EvaluationStateListRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiEvaluationStateFromJSON));
    }

    /**
     * Lists an overview of all evaluation visible to the current user.
     */
    async getApiV2EvaluationStateList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiEvaluationState>> {
        const response = await this.getApiV2EvaluationStateListRaw(initOverrides);
        return await response.value();
    }

}
