/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorStatus,
  QueryEventLog,
  QueryResultLog,
  SuccessStatus,
} from '../models/index';
import {
    ErrorStatusFromJSON,
    ErrorStatusToJSON,
    QueryEventLogFromJSON,
    QueryEventLogToJSON,
    QueryResultLogFromJSON,
    QueryResultLogToJSON,
    SuccessStatusFromJSON,
    SuccessStatusToJSON,
} from '../models/index';

export interface PostApiV2LogQueryByEvaluationIdRequest {
    evaluationId: string;
    session: string;
    queryEventLog?: QueryEventLog;
}

export interface PostApiV2LogResultByEvaluationIdRequest {
    evaluationId: string;
    session: string;
    queryResultLog?: QueryResultLog;
}

/**
 * 
 */
export class LogApi extends runtime.BaseAPI {

    /**
     * Creates request options for postApiV2LogQueryByEvaluationId without sending the request
     */
    async postApiV2LogQueryByEvaluationIdRequestOpts(requestParameters: PostApiV2LogQueryByEvaluationIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['evaluationId'] == null) {
            throw new runtime.RequiredError(
                'evaluationId',
                'Required parameter "evaluationId" was null or undefined when calling postApiV2LogQueryByEvaluationId().'
            );
        }

        if (requestParameters['session'] == null) {
            throw new runtime.RequiredError(
                'session',
                'Required parameter "session" was null or undefined when calling postApiV2LogQueryByEvaluationId().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['session'] != null) {
            queryParameters['session'] = requestParameters['session'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v2/log/query/{evaluationId}`;
        urlPath = urlPath.replace(`{${"evaluationId"}}`, encodeURIComponent(String(requestParameters['evaluationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QueryEventLogToJSON(requestParameters['queryEventLog']),
        };
    }

    /**
     * Accepts query logs from participants for the specified evaluation.
     */
    async postApiV2LogQueryByEvaluationIdRaw(requestParameters: PostApiV2LogQueryByEvaluationIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessStatus>> {
        const requestOptions = await this.postApiV2LogQueryByEvaluationIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessStatusFromJSON(jsonValue));
    }

    /**
     * Accepts query logs from participants for the specified evaluation.
     */
    async postApiV2LogQueryByEvaluationId(requestParameters: PostApiV2LogQueryByEvaluationIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessStatus> {
        const response = await this.postApiV2LogQueryByEvaluationIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postApiV2LogResultByEvaluationId without sending the request
     */
    async postApiV2LogResultByEvaluationIdRequestOpts(requestParameters: PostApiV2LogResultByEvaluationIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['evaluationId'] == null) {
            throw new runtime.RequiredError(
                'evaluationId',
                'Required parameter "evaluationId" was null or undefined when calling postApiV2LogResultByEvaluationId().'
            );
        }

        if (requestParameters['session'] == null) {
            throw new runtime.RequiredError(
                'session',
                'Required parameter "session" was null or undefined when calling postApiV2LogResultByEvaluationId().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['session'] != null) {
            queryParameters['session'] = requestParameters['session'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v2/log/result/{evaluationId}`;
        urlPath = urlPath.replace(`{${"evaluationId"}}`, encodeURIComponent(String(requestParameters['evaluationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QueryResultLogToJSON(requestParameters['queryResultLog']),
        };
    }

    /**
     * Accepts result logs from participants  for the specified evaluation.
     */
    async postApiV2LogResultByEvaluationIdRaw(requestParameters: PostApiV2LogResultByEvaluationIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessStatus>> {
        const requestOptions = await this.postApiV2LogResultByEvaluationIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessStatusFromJSON(jsonValue));
    }

    /**
     * Accepts result logs from participants  for the specified evaluation.
     */
    async postApiV2LogResultByEvaluationId(requestParameters: PostApiV2LogResultByEvaluationIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessStatus> {
        const response = await this.postApiV2LogResultByEvaluationIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
