/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CurrentTime,
} from '../models/index';
import {
    CurrentTimeFromJSON,
    CurrentTimeToJSON,
} from '../models/index';

/**
 * 
 */
export class StatusApi extends runtime.BaseAPI {

    /**
     * Creates request options for getApiV2StatusTime without sending the request
     */
    async getApiV2StatusTimeRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v2/status/time`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the current time on the server.
     */
    async getApiV2StatusTimeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CurrentTime>> {
        const requestOptions = await this.getApiV2StatusTimeRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CurrentTimeFromJSON(jsonValue));
    }

    /**
     * Returns the current time on the server.
     */
    async getApiV2StatusTime(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CurrentTime> {
        const response = await this.getApiV2StatusTimeRaw(initOverrides);
        return await response.value();
    }

}
