/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiClientSubmission,
  ErrorStatus,
  SuccessfulSubmissionsStatus,
} from '../models/index';
import {
    ApiClientSubmissionFromJSON,
    ApiClientSubmissionToJSON,
    ErrorStatusFromJSON,
    ErrorStatusToJSON,
    SuccessfulSubmissionsStatusFromJSON,
    SuccessfulSubmissionsStatusToJSON,
} from '../models/index';

export interface PostApiV2SubmitByEvaluationIdRequest {
    evaluationId: string;
    apiClientSubmission: ApiClientSubmission;
    session?: string;
}

/**
 * 
 */
export class SubmissionApi extends runtime.BaseAPI {

    /**
     * Creates request options for postApiV2SubmitByEvaluationId without sending the request
     */
    async postApiV2SubmitByEvaluationIdRequestOpts(requestParameters: PostApiV2SubmitByEvaluationIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['evaluationId'] == null) {
            throw new runtime.RequiredError(
                'evaluationId',
                'Required parameter "evaluationId" was null or undefined when calling postApiV2SubmitByEvaluationId().'
            );
        }

        if (requestParameters['apiClientSubmission'] == null) {
            throw new runtime.RequiredError(
                'apiClientSubmission',
                'Required parameter "apiClientSubmission" was null or undefined when calling postApiV2SubmitByEvaluationId().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['session'] != null) {
            queryParameters['session'] = requestParameters['session'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v2/submit/{evaluationId}`;
        urlPath = urlPath.replace(`{${"evaluationId"}}`, encodeURIComponent(String(requestParameters['evaluationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiClientSubmissionToJSON(requestParameters['apiClientSubmission']),
        };
    }

    /**
     * Endpoint to accept submissions.
     */
    async postApiV2SubmitByEvaluationIdRaw(requestParameters: PostApiV2SubmitByEvaluationIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessfulSubmissionsStatus>> {
        const requestOptions = await this.postApiV2SubmitByEvaluationIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessfulSubmissionsStatusFromJSON(jsonValue));
    }

    /**
     * Endpoint to accept submissions.
     */
    async postApiV2SubmitByEvaluationId(requestParameters: PostApiV2SubmitByEvaluationIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessfulSubmissionsStatus> {
        const response = await this.postApiV2SubmitByEvaluationIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
