/* tslint:disable */
/* eslint-disable */
/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.4
 *
 * The version of the OpenAPI document: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiUser,
  ApiUserRequest,
  ErrorStatus,
  LoginRequest,
  SuccessStatus,
} from '../models/index';
import {
    ApiUserFromJSON,
    ApiUserToJSON,
    ApiUserRequestFromJSON,
    ApiUserRequestToJSON,
    ErrorStatusFromJSON,
    ErrorStatusToJSON,
    LoginRequestFromJSON,
    LoginRequestToJSON,
    SuccessStatusFromJSON,
    SuccessStatusToJSON,
} from '../models/index';

export interface DeleteApiV2UserByUserIdRequest {
    userId: string;
}

export interface GetApiV2LogoutRequest {
    session?: string;
}

export interface GetApiV2UserByUserIdRequest {
    userId: string;
}

export interface GetApiV2UserSessionRequest {
    session?: string;
}

export interface PatchApiV2UserByUserIdRequest {
    userId: string;
    apiUserRequest?: ApiUserRequest;
}

export interface PostApiV2LoginRequest {
    loginRequest?: LoginRequest;
}

export interface PostApiV2UserRequest {
    apiUserRequest?: ApiUserRequest;
}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI {

    /**
     * Creates request options for deleteApiV2UserByUserId without sending the request
     */
    async deleteApiV2UserByUserIdRequestOpts(requestParameters: DeleteApiV2UserByUserIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling deleteApiV2UserByUserId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v2/user/{userId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deletes the specified user. Requires ADMIN privileges
     */
    async deleteApiV2UserByUserIdRaw(requestParameters: DeleteApiV2UserByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiUser>> {
        const requestOptions = await this.deleteApiV2UserByUserIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiUserFromJSON(jsonValue));
    }

    /**
     * Deletes the specified user. Requires ADMIN privileges
     */
    async deleteApiV2UserByUserId(requestParameters: DeleteApiV2UserByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiUser> {
        const response = await this.deleteApiV2UserByUserIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getApiV2Logout without sending the request
     */
    async getApiV2LogoutRequestOpts(requestParameters: GetApiV2LogoutRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['session'] != null) {
            queryParameters['session'] = requestParameters['session'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v2/logout`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Clears all user roles of the current session.
     */
    async getApiV2LogoutRaw(requestParameters: GetApiV2LogoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessStatus>> {
        const requestOptions = await this.getApiV2LogoutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessStatusFromJSON(jsonValue));
    }

    /**
     * Clears all user roles of the current session.
     */
    async getApiV2Logout(requestParameters: GetApiV2LogoutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessStatus> {
        const response = await this.getApiV2LogoutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getApiV2User without sending the request
     */
    async getApiV2UserRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v2/user`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get information about the current user.
     */
    async getApiV2UserRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiUser>> {
        const requestOptions = await this.getApiV2UserRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiUserFromJSON(jsonValue));
    }

    /**
     * Get information about the current user.
     */
    async getApiV2User(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiUser> {
        const response = await this.getApiV2UserRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getApiV2UserByUserId without sending the request
     */
    async getApiV2UserByUserIdRequestOpts(requestParameters: GetApiV2UserByUserIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getApiV2UserByUserId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v2/user/{userId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets details of the user with the given id.
     */
    async getApiV2UserByUserIdRaw(requestParameters: GetApiV2UserByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiUser>> {
        const requestOptions = await this.getApiV2UserByUserIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiUserFromJSON(jsonValue));
    }

    /**
     * Gets details of the user with the given id.
     */
    async getApiV2UserByUserId(requestParameters: GetApiV2UserByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiUser> {
        const response = await this.getApiV2UserByUserIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getApiV2UserSession without sending the request
     */
    async getApiV2UserSessionRequestOpts(requestParameters: GetApiV2UserSessionRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['session'] != null) {
            queryParameters['session'] = requestParameters['session'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v2/user/session`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get current sessionId
     */
    async getApiV2UserSessionRaw(requestParameters: GetApiV2UserSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.getApiV2UserSessionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get current sessionId
     */
    async getApiV2UserSession(requestParameters: GetApiV2UserSessionRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getApiV2UserSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchApiV2UserByUserId without sending the request
     */
    async patchApiV2UserByUserIdRequestOpts(requestParameters: PatchApiV2UserByUserIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling patchApiV2UserByUserId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v2/user/{userId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ApiUserRequestToJSON(requestParameters['apiUserRequest']),
        };
    }

    /**
     * Updates the specified user, if it exists. Anyone is allowed to update their data, however only ADMINs are allowed to update anyone.
     */
    async patchApiV2UserByUserIdRaw(requestParameters: PatchApiV2UserByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiUser>> {
        const requestOptions = await this.patchApiV2UserByUserIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiUserFromJSON(jsonValue));
    }

    /**
     * Updates the specified user, if it exists. Anyone is allowed to update their data, however only ADMINs are allowed to update anyone.
     */
    async patchApiV2UserByUserId(requestParameters: PatchApiV2UserByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiUser> {
        const response = await this.patchApiV2UserByUserIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postApiV2Login without sending the request
     */
    async postApiV2LoginRequestOpts(requestParameters: PostApiV2LoginRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v2/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRequestToJSON(requestParameters['loginRequest']),
        };
    }

    /**
     * Sets roles for session based on user account and returns a session cookie.
     */
    async postApiV2LoginRaw(requestParameters: PostApiV2LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiUser>> {
        const requestOptions = await this.postApiV2LoginRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiUserFromJSON(jsonValue));
    }

    /**
     * Sets roles for session based on user account and returns a session cookie.
     */
    async postApiV2Login(requestParameters: PostApiV2LoginRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiUser> {
        const response = await this.postApiV2LoginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postApiV2User without sending the request
     */
    async postApiV2UserRequestOpts(requestParameters: PostApiV2UserRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v2/user`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiUserRequestToJSON(requestParameters['apiUserRequest']),
        };
    }

    /**
     * Creates a new user, if the username is not already taken. Requires ADMIN privileges
     */
    async postApiV2UserRaw(requestParameters: PostApiV2UserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiUser>> {
        const requestOptions = await this.postApiV2UserRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiUserFromJSON(jsonValue));
    }

    /**
     * Creates a new user, if the username is not already taken. Requires ADMIN privileges
     */
    async postApiV2User(requestParameters: PostApiV2UserRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiUser> {
        const response = await this.postApiV2UserRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
